### ISSUE TITLE
Molecules(CIF and XYZ) generated from pyxtal_molecule don't match

### ISSUE THREAD

**Issue by sli259** [qzhu2017/PyXtal#102]
I am using the pyxtal_molecule.py to generate crystal structures for a molecule. It looks like the cif file and xyz file in the /out directory are different. I am using the p212121 space group, the 4 molecules in the cif file are more packed, while they are far separated in the xyz file. Can anyone tell me where goes wrong?

![SiH19C17S-cif](https://user-images.githubusercontent.com/24900061/95791496-18330280-0ca7-11eb-8cc0-4e8ec88943f2.png)
![S8C136H152Si8-xyz](https://user-images.githubusercontent.com/24900061/95791501-18cb9900-0ca7-11eb-8355-f82684884c5d.png)

**Comment by qzhu2017** [comment]
@sli259 

They are the same structures. In the xyz format, you are seeing the molecules belonging to different unit cells. In the cif file, we somehow move all molecules close to a single unit cell. If you are dealing with the crystals, I suggest you stay with the cif file.

**Comment by sli259** [comment]
Thanks! That make sense to me now. I am wondering if there is a way to generate an xyz file that has the unit cell packing. Also, I am trying with the molecular_crystal module to generate a crystal and then write to file, somehow I can only choose the fmt=cif, the fmt=xyz won't work.

**Comment by qzhu2017** [comment]
@sli259 

I just updated the documentation site. The following link may be useful
https://pyxtal.readthedocs.io/en/latest/Usage.html#supports-for-different-file-formats

**Comment by sli259** [comment]
@qzhu2017 
Thank you Prof. Zhu, the extxyz works for me, however, the resulting xyz files still have molecules from different unit cells. Is there way to shift the high symmetry space group to P1 and presents all the molecules in the unit cell? For example, if I am creating a P2 crystals, how can I save the coordinates of two molecules in the same xyz file?
I also noticed another issue, when I tried to generate a few random crystals for a small molecule, say benzene. I used following code:
_mol = molecular_crystal(3, ['benz.xyz'], [2])
mol.to_file(filename='benz.cif')_
In some cases, there are two molecules' coordinates in the cif file, and some cases, there is only one. I found this only happened for small molecules. Was there something I didn't specify? or how can I avoid this? 
Thank you!

**Comment by qzhu2017** [comment]
@sli259 
I will add a function to move the molecule close to the unit cell later. However, I still don't understand why do need the xyz format. Shouldn't it be more convenient to work on the format like cif or POSCAR if you are dealing with the periodic systems?

**Comment by sli259** [comment]
Thanks for the help. I just recently started this project and I think there are a lot more for me to learn about the concept. 
I am trying to use the ASE optimizer to optimize the random crystal that created by PyXtal. I am able to create the random crystals and use Pymatgen to shift them to P1 symmetry. But the cif file from Pymatgen has PBC applied. 
I need all the coordinates for all atoms in that P1 symmetry. Because of the periodicity, once I converted the file to xyz, the periodicity was lost, and it end up with isolated atoms or molecular fractions. This causes issue during the local optimization from ASE as the molecules collapsed during the process.
I also tried to use your to_ase function but it seems that the resulting coordinates are also molecules from adjacent cells. So this won't work for me. 
I don't know if there is options to use crystal structure directly on ASE, it would be very helpful if you can give me some suggestions. Best!

**Comment by qzhu2017** [comment]
@sli259 
I just made a commit to resolve this issue. Please update your code and let me know if it works.

Btw, you can list your scripts here. There should be a much easier way to do optimization through ASE. What you described above seems to be too complicated...
