### ISSUE TITLE
Atomic order after crystal generation

### ISSUE THREAD

**Issue by sli259** [qzhu2017/PyXtal#105]
I found that after I generated the random crystal, the atomic index of the molecule is reordered base on the atomic number. 
For example, I used benzene as the input, and creating a P2 space group then output the cif file. My starting input benzene has the atom ordered as:
C x y z
H ...
C ...
H ...
C ...
H ...
...
Once I output the CIF or XYZ file, the order became:
H 
H
H
H
...
C
C
C
C
...
This will be the same order when I convert it to ASE format. Is there a way to maintain the atomic index as it was in the output file during this process? So it will be like:
C
H
C
H(1st molecular)
...(then
C
H
C
H(2nd molecular)

This will be very helpful if we want to do intermolecular relation analysis. 
Thanks!

**Comment by qzhu2017** [comment]
@sli259 
Check my recent update in the documentation.
https://pyxtal.readthedocs.io/en/latest/Usage.html#supports-for-different-file-formats

<img width="712" alt="image" src="https://user-images.githubusercontent.com/29445366/96897349-5a94d600-1443-11eb-85e0-6b06a9035949.png">

In addition, please star our code in the first page if you think this code is useful for your research.

**Comment by sli259** [comment]
Thank you for your quick response, Dr. Zhu. This is super helpful for my research! 

Best,
Shi
