### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'verbosity'

### ISSUE THREAD

**Issue by nitin8sp** [qzhu2017/PyXtal#106]
Hi, I just installed pyxtal. test script ran successfully. But when I issues the command $ pyxtal_atom.py -e C -n 60 -d 0 -s Ih
to check the generation of C60 structure. Following error came:
Traceback (most recent call last):
  File "/home/nitin/.local/bin/pyxtal_atom.py", line 118, in <module>
    verbosity = options.verbosity
AttributeError: 'Namespace' object has no attribute 'verbosity'

**Comment by qzhu2017** [comment]
@nitin8sp 
This should be fixed after my latest commit 0113d38fcac822b790e233f0a7a393c426482520

I am not going to update the package in PyPI very soon. So you need to do the following to get it work

```
$ pip install --upgrade git+https://github.com/qzhu2017/PyXtal.git@master
```

Btw, please star our code in the main page if you think this code is useful.
