### ISSUE TITLE
bug for print(struture)...

### ISSUE THREAD

**Issue by usccolumbia** [qzhu2017/PyXtal#114]
when I run this:

my_crystal = pyxtal()
my_crystal.from_random(3, 99, ['Ba','Ti','O'], [1,1,3])
print(my_crystal)

it reports error
  File "test-cifreader.py", line 15, in <module>
    print(s)
  File "/xxx/p3/lib/python3.7/site-packages/pyxtal/__init__.py", line 117, in __str__
    s = "------Crystal from {:s}------".format(self.source)
AttributeError: 'pyxtal' object has no attribute 'source'

**Comment by qzhu2017** [comment]
@usccolumbia Are you sure that you updated your pyxtal to v0.1.4?
```
pip install --upgrade pyxtal
```
or 
```
pip install pyxtal==0.1.4
```

```python
>>> import pyxtal as px
>>> px.__version__
'0.1.4'
>>> from pyxtal import pyxtal
>>> my_crystal = pyxtal()
>>> my_crystal.from_random(3, 99, ['Ba','Ti','O'], [1,1,3])
>>> my_crystal
------Crystal from random------
Dimension: 3
Composition: Ba1Ti1O3
Group: P4mm (99)
tetragonal lattice:   3.1193   3.1193  10.6772  90.0000  90.0000  90.0000
Wyckoff sites:
	Ba @ [0.5000 0.5000 0.5240], WP:  1b, Site symmetry: 4 m m
	Ti @ [0.5000 0.5000 0.1064], WP:  1b, Site symmetry: 4 m m
	 O @ [0.5000 0.0000 0.5654], WP:  2c, Site symmetry: 2 mm .
	 O @ [0.0000 0.0000 0.1165], WP:  1a, Site symmetry: 4 m m
```
