### ISSUE TITLE
random_crystal Methods to_ase and to_pymatgen  are gone from 0.1.4 and later

### ISSUE THREAD

**Issue by LuciusV** [qzhu2017/PyXtal#122]
Hi, 
Please, add them back for backward compatibility

**Comment by qzhu2017** [comment]
From v0.1.3, we changed the way to generate the crystal. Now please every structure will go to the pyxtal object as follows.

https://pyxtal.readthedocs.io/en/latest/pyxtal.html
```python
>>> from pyxtal import pyxtal
>>> struc = pyxtal()
>>> struc.from_random(3, 227, ['C'], [8])
>>> pmg_struc = struc.to_pymatgen()
>>> ase_struc = struc.to_ase()
```

**Comment by LuciusV** [comment]
Thank you, I adapted my scripts to this change.
