### ISSUE TITLE
Pyxtal tests fails on build molecular structures

### ISSUE THREAD

**Issue by Haru-Fujimura** [qzhu2017/PyXtal#126]
Here is the error: 
<details>
```
===Testing generation of molecular 3D crystals. This may take some time. ===
  Spacegroup #  |Generated (SPG)|Generated (PMG)|  Time Elapsed
Traceback (most recent call last):
  File "/home/haru/miniconda3/envs/group/bin/pyxtal_test.py", line 4, in <module>
    __import__('pkg_resources').run_script('pyxtal==0.1.7', 'pyxtal_test.py')
  File "/home/haru/miniconda3/envs/group/lib/python3.8/site-packages/pkg_resources/__init__.py", line 650, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1446, in run_script
    exec(code, namespace, namespace)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/site-packages/pyxtal-0.1.7-py3.8.egg/EGG-INFO/scripts/pyxtal_test.py", line 1321, in <module>
    eval(modules_lib[module])
  File "<string>", line 1, in <module>
  File "/home/haru/miniconda3/envs/group/lib/python3.8/site-packages/pyxtal-0.1.7-py3.8.egg/EGG-INFO/scripts/pyxtal_test.py", line 373, in test_molecular
    rand_crystal.from_random(3, sg, ["H2O"], [multiplicity], 2.5)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/site-packages/pyxtal-0.1.7-py3.8.egg/pyxtal/__init__.py", line 223, in from_random
    struc = molecular_crystal(group, species, numIons, factor, 
  File "/home/haru/miniconda3/envs/group/lib/python3.8/site-packages/pyxtal-0.1.7-py3.8.egg/pyxtal/molecular_crystal.py", line 73, in __init__
    self.init_common(
  File "/home/haru/miniconda3/envs/group/lib/python3.8/site-packages/pyxtal-0.1.7-py3.8.egg/pyxtal/molecular_crystal.py", line 215, in init_common
    self.generate_crystal()
  File "/home/haru/miniconda3/envs/group/lib/python3.8/site-packages/pyxtal-0.1.7-py3.8.egg/pyxtal/molecular_crystal.py", line 457, in generate_crystal
    output = self._generate_coords()
  File "/home/haru/miniconda3/envs/group/lib/python3.8/site-packages/pyxtal-0.1.7-py3.8.egg/pyxtal/molecular_crystal.py", line 479, in _generate_coords
    output = self._generate_mol_wyckoffs(
  File "/home/haru/miniconda3/envs/group/lib/python3.8/site-packages/pyxtal-0.1.7-py3.8.egg/pyxtal/molecular_crystal.py", line 546, in _generate_mol_wyckoffs
    ms0 = self._generate_orientation(pyxtal_mol, pt, oris, wp)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/site-packages/pyxtal-0.1.7-py3.8.egg/pyxtal/molecular_crystal.py", line 588, in _generate_orientation
    ori = random.choice(oris).copy()
  File "/home/haru/miniconda3/envs/group/lib/python3.8/site-packages/pyxtal-0.1.7-py3.8.egg/pyxtal/molecule.py", line 311, in copy
    return deepcopy(self)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 264, in _reconstruct
    y = func(*args)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 263, in <genexpr>
    args = (deepcopy(arg, memo) for arg in args)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 210, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 210, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
  File "stringsource", line 2, in View.MemoryView._memoryviewslice.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```
</details>

and here are the dependencies i have in my conda environment. 

<details>
```
_libgcc_mutex             0.1                        main  
ase                       3.20.1                   pypi_0    pypi
ca-certificates           2020.12.8            h06a4308_0  
cairo                     1.16.0            h18b612c_1001    conda-forge
certifi                   2020.12.5        py38h06a4308_0  
chardet                   4.0.0                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.4               h5ab3b9f_0  
future                    0.18.2                   pypi_0    pypi
glib                      2.66.1               h92f7085_0  
icu                       58.2                 he6710b0_3  
idna                      2.10                     pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
llvmlite                  0.35.0                   pypi_0    pypi
matplotlib                3.3.3                    pypi_0    pypi
monty                     4.0.2                    pypi_0    pypi
mpmath                    1.1.0                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
networkx                  2.5                      pypi_0    pypi
numba                     0.52.0                   pypi_0    pypi
numpy                     1.20.0rc2                pypi_0    pypi
openbabel                 3.1.1            py38hf4b5c11_1    conda-forge
openssl                   1.1.1i               h27cfd23_0  
palettable                3.3.0                    pypi_0    pypi
pandas                    1.2.0                    pypi_0    pypi
pcre                      8.44                 he6710b0_0  
pillow                    8.1.0                    pypi_0    pypi
pip                       20.3.3           py38h06a4308_0  
pixman                    0.38.0            h516909a_1003    conda-forge
plotly                    4.14.3                   pypi_0    pypi
py3dmol                   0.9.1                    pypi_0    pypi
pymatgen                  2020.12.31               pypi_0    pypi
pyparsing                 3.0.0b2                  pypi_0    pypi
python                    3.8.5                h7579374_1  
python-dateutil           2.8.1                    pypi_0    pypi
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.5                   pypi_0    pypi
pyxtal                    0.1.7                    pypi_0    pypi
readline                  8.0                  h7b6447c_0  
requests                  2.25.1                   pypi_0    pypi
ruamel-yaml               0.16.12                  pypi_0    pypi
ruamel-yaml-clib          0.2.2                    pypi_0    pypi
scipy                     1.6.0                    pypi_0    pypi
setuptools                51.1.2           py38h06a4308_4  
six                       1.15.0                   pypi_0    pypi
spglib                    1.16.0                   pypi_0    pypi
sqlite                    3.33.0               h62c20be_0  
swig                      3.0.12               h38cdd7d_3  
sympy                     1.7.1                    pypi_0    pypi
tabulate                  0.8.7                    pypi_0    pypi
tk                        8.6.10               hbc83047_0  
tzdata                    2020d                h14c3975_0  
uncertainties             3.1.5                    pypi_0    pypi
urllib3                   1.26.2                   pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.12               h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h27cfd23_1007  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  
```
</details>

I am not sure where the problem lies, during installation there were few problems related to numpy deprecated syntax, but nothing of serious note (i thought)

**Comment by qzhu2017** [comment]
@Haru-Fujimura 
This problem appeared only recently. It also failed in the GitHub workflow. 
It seems to be related to the `copy` function.
However, I cannot reproduce the same error in my own environments (MAC and Ubuntu.)
I am glad that you can reproduce this error. May I suggest the followings,

- Which OS and python version are you using?
- Can you checkout PyXtal v0.1.6 and v0.1.5 and see if the test script work?

**Comment by Haru-Fujimura** [comment]
I am on Ubuntu 20.04. The python version should be 3.8.5 (sorry for my bad markdown)

How would i get PyXtal v0.1.6 and v0.1.5 ?

**Comment by qzhu2017** [comment]
@Haru-Fujimura 
- If you get the code via `git clone`, go to the directory where you put PyXtal, type `git checkout v0.1.6`
- If you get the code via `pip install`, just type `pip install pyxtal==0.1.6`

Please let me know how it works. This issue appeared only recently after we upgraded to `v0.1.7`. However, I never hit this error on my own environments.

**Comment by Haru-Fujimura** [comment]
The test continues to fail, note that i did 
`git checkout v0.1.6` and also `pip remove pyxtal` then i reinstalled with `python setup.py install`

[erors.txt](https://github.com/qzhu2017/PyXtal/files/5810939/erors.txt)

**Comment by qzhu2017** [comment]
Thanks for sending the details. I suspect this is related to some major update in ubuntu. I will update my progress here when I have time.

**Comment by qzhu2017** [comment]
@Haru-Fujimura 
```python
from pyxtal.molecule import Orientation
import numpy as np
from copy import deepcopy

ex1 = Orientation(np.eye(3))
ex2 = Orientation(np.eye(3))
print(ex1)
print(ex2)

copies = []
copies.append(ex1)
copies.append(ex2)
print("doing deepcopy------------")
dummy = deepcopy(copies)
print(dummy)
```
Can you try to run the above script and see if it works?

**Comment by Haru-Fujimura** [comment]
Hi,

This yields

`python ../pyxt.py 
-------PyXtal.molecule.Orientation class----
degree of freedom: 2
Rotation matrix:
 1.000  0.000  0.000
 0.000  1.000  0.000
 0.000  0.000  1.000

-------PyXtal.molecule.Orientation class----
degree of freedom: 2
Rotation matrix:
 1.000  0.000  0.000
 0.000  1.000  0.000
 0.000  0.000  1.000

doing deepcopy------------
Traceback (most recent call last):
  File "../pyxt.py", line 14, in <module>
    dummy = deepcopy(copies)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 205, in _deepcopy_list
    append(deepcopy(a, memo))
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 264, in _reconstruct
    y = func(*args)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 263, in <genexpr>
    args = (deepcopy(arg, memo) for arg in args)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 210, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 210, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/home/haru/miniconda3/envs/group/lib/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
  File "stringsource", line 2, in View.MemoryView._memoryviewslice.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
`

**Comment by qzhu2017** [comment]
I see. Somehow the `deepcopy` method can no longer do the job properly. Do you have a few minutes for a quick video meeting? I want to try some commands and see how they work on your computer.

**Comment by Haru-Fujimura** [comment]
id rather not do a video meeting. Give me the commands and I will do them on the problem computer when i have time.

**Comment by qzhu2017** [comment]
@Haru-Fujimura 

```python
from pyxtal.molecule import Orientation
import numpy as np
from copy import deepcopy

# copy numpy
a = np.eye(3)
dummy = deepcopy(a)

# copy ase atoms
from ase.build import bulk
test = bulk('Si', 'diamond', a=5.459, cubic=True)
test1 = deepcopy(test)

# copy orientation
ex1 = Orientation(np.eye(3))
ex2 = Orientation(np.eye(3))
print(ex1)
print(ex2)

copies = []
copies.append(ex1)
copies.append(ex2)
print("doing deepcopy------------")
dummy = deepcopy(copies)
print(dummy)
```

Can you try to run the above code? I want to know when the `copy` function fails

**Comment by Haru-Fujimura** [comment]
When run, the above code outputs:

(group) zeru@ZOS3:~/installs$ python pyxtaldeepcopytest.py 
-------PyXtal.molecule.Orientation class----
degree of freedom: 2
Rotation matrix:
 1.000  0.000  0.000
 0.000  1.000  0.000
 0.000  0.000  1.000

-------PyXtal.molecule.Orientation class----
degree of freedom: 2
Rotation matrix:
 1.000  0.000  0.000
 0.000  1.000  0.000
 0.000  0.000  1.000

doing deepcopy------------
[-------PyXtal.molecule.Orientation class----
degree of freedom: 2
Rotation matrix:
 1.000  0.000  0.000
 0.000  1.000  0.000
 0.000  0.000  1.000
, -------PyXtal.molecule.Orientation class----
degree of freedom: 2
Rotation matrix:
 1.000  0.000  0.000
 0.000  1.000  0.000
 0.000  0.000  1.000
]

**Comment by qzhu2017** [comment]
@Haru-Fujimura This is weird. The same function works in the new run. But it failed in the previous code. I think I will need to find a machine which has the same environment and test it there. Thanks

**Comment by Tomoki-YAMASHITA** [comment]
I also encountered the same issue.

Both first (https://github.com/qzhu2017/PyXtal/issues/126#issuecomment-759750372)
and second  (https://github.com/qzhu2017/PyXtal/issues/126#issuecomment-761225737) codes did NOT work using Python 3.8.x and PyXtal 0.1.8 (Linux (built from source) and Mac (homebrew). ). I did not use anaconda.

But with PyXtal 0.1.6, both codes worked.

Haru-Fujimura used ver0.1.6 for the second run, doesn't he?

**Comment by qzhu2017** [comment]
@Tomoki-YAMASHITA 
That's strange. I believe that the problem is related to the `deepcopy` function. However, there is no obvious change between v0.1.6 and v0.1.8. I don't know why it fails for v0.1.8.

I haven't found a platform to reproduce these bugs.

**Comment by Tomoki-YAMASHITA** [comment]
@qzhu2017 
v0.1.8 worked on one of the Linux machine I use, then I found that scipy v1.6.0 causes this error.
When I downgraded SciPy from v1.6.0 to v1.5.4, PyXtal v0.1.8 worked without the error on my MacBook.
I consider this problem is caused by scipy v1.6.0 x deepcopy, not by pyxtal v0.1.7 or v0.1.8.

**Comment by qzhu2017** [comment]
@Tomoki-YAMASHITA 
Thank you so much!

Following your inspection, I rewrote the SciPy dependence in the `setup.py` and `requirements.txt`. Now it passed the GitHub workflow 
https://github.com/qzhu2017/PyXtal/actions

We haven't been able to pass the workflow since last December.

**Comment by qzhu2017** [comment]
https://github.com/scipy/scipy/issues/13358
This issue is supposed to be fixed in a new scipy release
