### ISSUE TITLE
molecular_crystal has no attribute 'to_ase' or 'to_file'?

### ISSUE THREAD

**Issue by sli259** [qzhu2017/PyXtal#127]
I used this script a well ago on another machine and it worked fine. But recently I installed PyXtal on a new machine and the same code failed with this error:
AttributeError: 'molecular_crystal' object has no attribute 'to_ase'

Here is part of the code, is there anything changed to the source?

```
from pyxtal.molecular_crystal import molecular_crystal

mol = molecular_crystal(2, ['input.xyz'], [2])
ase_struc = mol.to_ase(resort=False)

```

**Comment by qzhu2017** [comment]
We updated the code recently. The molecular crystal will be generated as described in the following link

https://pyxtal.readthedocs.io/en/latest/Usage.html#random-molecular-crystals

**Comment by sli259** [comment]
@qzhu2017 
Thank you prof. Zhu, I was able to use the new code to set up my work, but I found the new approach seems to fail more while generate crystals. 

```
    raise RuntimeError("It takes long time to generate the structure, check inputs")
RuntimeError: It takes long time to generate the structure, check inputs
```
I am randomly sampling through all space groups to generate 1 crystal for each spg. and this happed for many space groups, which never happened with the old molecular_crystal module. Can you let me know how to avoid this?

Shi

**Comment by sli259** [comment]
Here is an example code leads to this error:

```
from pyxtal import pyxtal
from ase.io import read
from range_key_dict import RangeKeyDict
import random
import os

#import numpy as np
#import scipy


spg_nmol = RangeKeyDict({(1, 2):'1', (2, 10): '2', (10, 47): '4', (47, 75): '8', (75, 83): '4', (83, 123): '8', (123, 143): '16', (143, 162): '6', (162, 168):'12', (168, 175): '6', (175, 191):'12', (191, 195): '24', (195, 200): '12', (200, 221): '24', (221, 231): '48'})

#orgSPG = [19, 4, 61, 33, 92, 18, 15, 7, 144, 76, 43, 56, 9, 13, 5, 169, 29, 88, 147, 60, 14]


def optXtal(spg, nmol, filename):
    crystal = pyxtal(molecular=True)
    crystal.from_random(3, spg, [filename], [nmol])
    ase_struc = crystal.to_ase(resort=False)
    ase_struc.write('crystal.xyz', format='extxyz')


N = 1
for i in range(N):
#    spg = random.randint(2, 230)
    spg = 43
    nmol = int(spg_nmol[spg])
    f = 'input.xyz'
    mol = read(f)
    optXtal(spg, nmol, f)

```

My input file is an xyz from other conformer generators, which looks like this:
```
31
title
C 4.50680 1.61290 0.20280
C 4.29990 0.45330 -0.75590
O 3.74260 -0.67100 -0.07780
C 2.38360 -0.79490 -0.00640
C 1.94370 -1.99900 0.54300
C 0.57990 -2.26390 0.68230
C -0.37410 -1.32100 0.27580
C -1.75040 -1.56920 0.40810
C -2.70620 -0.62300 0.00350
C -4.08290 -0.86950 0.13510
C -5.02070 0.08100 -0.27120
C -4.59460 1.28920 -0.81390
C -3.23010 1.54880 -0.95110
C -2.27390 0.60230 -0.54690
C -0.89690 0.84890 -0.67870
C 0.06090 -0.09740 -0.27520
C 1.44100 0.15210 -0.40850
H 4.99920 2.44870 -0.30250
H 5.12490 1.30200 1.05160
H 3.55740 1.96630 0.61570
H 3.72300 0.73960 -1.64220
H 5.28040 0.13460 -1.12790
H 2.67040 -2.74100 0.86490
H 0.27110 -3.21370 1.11250
H -2.08320 -2.51410 0.83360
H -4.43540 -1.80800 0.55710
H -6.08260 -0.12340 -0.16340
H -5.32320 2.03080 -1.13090
H -2.91710 2.49920 -1.37760
H -0.56580 1.79480 -1.10340
H 1.75200 1.10470 -0.82390

```

Thank you so much for helping me. 

Shi

**Comment by sli259** [comment]
@qzhu2017 
I found this also applied to simple molecules for several space groups:

```
from pyxtal import pyxtal

my_crystal = pyxtal(molecular=True)
my_crystal.from_random(3, 9, ['H2O'], [2])
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-d7b315d2111a> in <module>
      2 
      3 my_crystal = pyxtal(molecular=True)
----> 4 my_crystal.from_random(3, 9, ['H2O'], [2])

~/miniconda3/lib/python3.7/site-packages/pyxtal/__init__.py in from_random(self, dim, group, species, numIons, factor, thickness, area, lattice, sites, conventional, diag, t_factor, max_count, force_pass)
    250 
    251             if count >= max_count:
--> 252                 raise RuntimeError("It takes long time to generate the structure, check inputs")
    253 
    254         if quit:

RuntimeError: It takes long time to generate the structure, check inputs
```
however, this works if I change it to
`my_crystal.from_random(3, 9, ['H2O'], [4])`

As you can see from my earlier code, I used a dictionary to pass the number of molecules needed for each space group, I think spg 9 should have 2 molecules, instead of 4. But it doesn't make sense that why it couldn't fit 2 molecules into the crystal. 

In fact, if I run through all space groups, there are 27 of them couldn't generate structure due to this error. 
Can you look into it and help me with this? 

Thank you!
Shi

**Comment by qzhu2017** [comment]
Try to follow the example here:

https://github.com/qzhu2017/PyXtal/blob/8cdd44ccdfbc27bced35b305ec796ce3bcdcfa5e/examples/example_07_3D_ICE_lammps.py#L42-48

**Comment by sli259** [comment]
Thanks Dr. Zhu, I have tried to use this part of the code, but it doesn't work for some of my molecules. The time to generate a structure takes too long without any valid one. I attached one of the structure I have here. 

I am wondering if there is a way for me to go back use the previous version. 

[input.log](https://github.com/qzhu2017/PyXtal/files/5858010/input.log)

**Comment by qzhu2017** [comment]
@sli259 

Can you send me the entire script to repeat your calculation?

**Comment by qzhu2017** [comment]
@sli259  Sorry for the delay response. I just realized that you need to specify that `conventional=False` when you call the `from_random` function. Since v-0.1.5, we change the default to call the number of atoms based on the conventional cell (it was primitive cell before).

The following code should work. Please close this issue if it works on your computer as well.


```python
from pyxtal import pyxtal
from range_key_dict import RangeKeyDict
import random

#import numpy as np
#import scipy


spg_nmol = RangeKeyDict({(1, 2):'1', (2, 10): '2', (10, 47): '4', (47, 75): '8', (75, 83): '4', (83, 123): '8', (123, 143): '16', (143, 162): '6', (162, 168):'12', (168, 175): '6', (175, 191):'12', (191, 195): '24', (195, 200): '12', (200, 221): '24', (221, 231): '48'})

#orgSPG = [19, 4, 61, 33, 92, 18, 15, 7, 144, 76, 43, 56, 9, 13, 5, 169, 29, 88, 147, 60, 14]


def optXtal(spg, nmol, filename):
    crystal = pyxtal(molecular=True)
    while True:
        crystal.from_random(3, spg, [filename], [nmol], force_pass=True, conventional=False)
        if crystal.valid:
            break
    print(crystal)
    ase_struc = crystal.to_ase(resort=False)
    ase_struc.write('crystal.xyz', format='extxyz')


N = 10
for i in range(N):
    spg = 43
    nmol = int(spg_nmol[spg])
    f = 'input.xyz'
    optXtal(spg, nmol, f)
```

**Comment by sli259** [comment]
@qzhu2017 
This does work for my code. Thank you for your help, I will close this issue.
