### ISSUE TITLE
incorrect crystal generation from seed

### ISSUE THREAD

**Issue by gpetretto** [qzhu2017/PyXtal#128]
Dear developers, I have been trying to perform some analysis on a structure and apparently pyxtal fails to import it correctly.
Here is the structure:
https://gist.github.com/gpetretto/8f9849426b8eb465f89cf883b036fd98
and here is a piece of code demonstrating the issue. 
```
from pymatgen import Structure
from pymatgen.analysis.structure_matcher import StructureMatcher
from pyxtal import pyxtal


s = Structure.from_file("FAU.cif")

c = pyxtal()
c.from_seed(s)
sc = c.to_pymatgen()
sc.to(filename="conv.cif")

sm = StructureMatcher()
print(sm.fit(s, sc))
```

Aside from the StructureMatcher failing, just looking at the final Structure is enough to tell that it is completely different from the original one.

I tried to check the code, but it seems that there is no problem in the conversion to/from pymatgen and the issue seems to happen when the instances of `atom_site` are generated. More precisely when the sym_ops are applied in the `search_position` and `update` method, but I could not identify the exact source of the issue. I am not sure if this will be of much help...

**Comment by qzhu2017** [comment]
@gpetretto Thanks for opening this issue. The problem should have been fixed in my recent commit (74bc804)

However, I am not sure if my fix will apply to any cif file. Please try more examples and let me know if you find any problem on other structures.

**Comment by gpetretto** [comment]
Dear @qzhu2017, thanks a lot for the quick fix. I have run a systematic test for all the structures in the [zeolite database](http://www.iza-structure.org/databases/) and for 20000 structures from the [materials project](https://www.materialsproject.org/).   
Here you can find the cif files for all those that failed the `StructureMatcher` test:
https://drive.google.com/file/d/1b2oHKMIFcl7C9vWEX3hJBEk-ysfYL9Os/view?usp=sharing

 For several of them I checked explicitly that indeed the converted structures did not match the original ones

**Comment by qzhu2017** [comment]
We are using Spglib/Pymatgen to symmetrize the input structure. Essentially, this is done through spglib. However, I have some trouble in interpreting the spglib output. 
- Spglib output the wyckoff symbol, however, sometimes the output coordinates are inconsistent with the desired wyckoff relation. Just posted an issue there (https://github.com/spglib/spglib/issues/114).
- sometime, Spglib failed to return the desired symmetry.

**Comment by qzhu2017** [comment]
@gpetretto I have fixed most of the issues as discussed in (spglib/spglib#114).

In my test, all zeolites return the same structures after symmetrization. Most of mp structures work as well.
You can try the following code

```python
from pymatgen import Structure
from pymatgen.analysis.structure_matcher import StructureMatcher
from pyxtal import pyxtal
from glob import glob

path = "cif_files/wrong_cif_zeolites/"
path = "cif_files/wrong_cif_mp/"

for f in glob(path+'/*.cif'):
    try:
        s = Structure.from_file(f)
        c = pyxtal()
        c.from_seed(s, tol=1e-6)
        sc = c.to_pymatgen()
        sm = StructureMatcher()
        if not sm.fit(s, sc):
            print(f, c.group.number, sm.fit(s, sc))
    except:
        print(f, "wrong")
```

I checked some structures which return mismatch. However, it seems that they are somewhat due to numerical issues.

One remaining issue, spglib sometime detects a wrong symmetry. For instance, the structure `LTN.cif` has a space group symmetry Fd-3m, but spglib returns a `P2` symmetry.

This happens to only a few cases. Will check it later.

**Comment by qzhu2017** [comment]
For the `LAS.cif`, if I slightly change the atomic coordinates, the symmetry will be found correctly. So it appears to be the decimal issue. 

<img width="824" alt="image" src="https://user-images.githubusercontent.com/29445366/106091026-5fbb8e00-60e0-11eb-938d-d7d6f0eb0023.png">

**Comment by qzhu2017** [comment]
Checked the failed mp structures. It is highly to be due to decimal issue.
