### ISSUE TITLE
Feature request: determinstic random state

### ISSUE THREAD

**Issue by rmcgibbo** [qzhu2017/PyXtal#133]
Small feature request: I'd like to be able to get deterministic results from pyxtal. That is, I'd like to set the random seed at the beginning of my script, and then get the same crystal out of I run the script twice with the same random seed.

I tried setting both `numpy.random.seed(0)` and `random.seed(0)`, but it seems like that is not quite sufficient. I believe at least one of the reasons is https://github.com/qzhu2017/PyXtal/blob/b288f8844b52f9298e01281a2e406744627a2620/pyxtal/lattice.py#L470, and any other place where `numpy.random.RandomState()` is called without a seed, because that function initializes the PRNG with data from `/dev/urandom`.

**Comment by qzhu2017** [comment]
This should be easy. I actually did something similar in some of my old script. I will try to implement this feature some time later.

**Comment by qzhu2017** [comment]
@rmcgibbo 

Please check out the version after my commit 7bf04ef and run the following script

```python
from random import choice, seed
import numpy as np
from pyxtal import pyxtal

seed(0)
np.random.seed(0)
for i in range(5):
    while True:
        sg, numIons = choice(range(3,231)), 4
        struc = pyxtal()
        struc.from_random(3, sg, ["C"], [numIons], force_pass=True) 
        if struc.valid:
            print(struc)
            break

for i in range(5):
    while True:
        sg, numIons = choice(range(3,231)), 4
        struc = pyxtal(molecular=True)
        struc.from_random(3, sg, ["H2O"], [numIons], force_pass=True) 
        if struc.valid:
            print(struc)
            break
```

Is this what you want?

**Comment by rmcgibbo** [comment]
Yep, looks great. Thanks!
