### ISSUE TITLE
Installation failed 

### ISSUE THREAD

**Issue by nujabse** [qzhu2017/PyXtal#140]
I tried to install pyxtal in Mac OS 10.15.7, Python 3.7. Running installation using `pip install --upgrade git+https://github.com/qzhu2017/PyXtal.git@master `, the installation was successful, however, when I test the installation using `pyxtal_test.py` command, there is an error saying that `pyxtal.symmetry` module failed. The output of `pyxtal_test.py` is :
```python
====== Testing functionality for pyXtal version 0.1dev ======
Importing sys...
Success!
Importing numpy...
Success!
Importing pymatgen...
Success!
Importing pandas...
Success!
Importing spglib...
Success!
Importing ase...
Success!
=== Testing modules ===
pyxtal.database.element
  class Element
pyxtal.database.hall
  hall_from_hm
pyxtal.database.collection
  Collection
pyxtal.operations
  angle
  is_orthogonal
  rotate_vector
  are_equal
  class OperationAnalyzer
  class Orientation
~~~ Error:
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/pyxtal/bin/pyxtal_test.py", line 1042, in test_modules
    o = Orientation.from_constraint(v1, c1)
AttributeError: type object 'Orientation' has no attribute 'from_constraint'
~~~ Failed module ~~~
pyxtal.symmetry
  get_wyckoffs (may take a moment)
  get_wyckoff_symmetry (may take a moment)
  get_wyckoffs_generators (may take a moment)
  letter_from_index
  index_from_letter
  jk_from_i
  i_from_jk
  ss_string_from_ops
  Wyckoff_position
  Group
pyxtal.molecule
  reoriented_molecule
  orientation_in_wyckoff_position
===
One or more modules failed. Try reinstalling the package.
```
Is there any help on this? Thanks!

**Comment by qzhu2017** [comment]
@nujabse Thanks for bring up this issue. The `from_constraint` function was no longer used.  I just fixed it. You can update your code now from the master branch. If you can wait, I will also send a new release of v0.2.4 in a couple of days. I will close this issue after v0.2.4 is out.

**Comment by nujabse** [comment]
Thanks for your help! I have just tested reinstalling Pyxtal, and it runs nicely.
