### ISSUE TITLE
Repeated calls to check_compatible from pyxtal.from_random()

### ISSUE THREAD

**Issue by CompRhys** [qzhu2017/PyXtal#146]
When we call `pyxtal.from_random()` in the main while loop the code calls `random_crystal.check_compatible()` repeated up to `max_count` times rather than just once. For large crystals this can take up a lot of time to end up with no valid structure. I believe it would be best to raise a `ValueError` when the crystal is not compatible and then allow users to catch this error using the typical python machinery if they don't want their code to crash for random structure inputs.

**Comment by qzhu2017** [comment]
@CompRhys Thanks for the kind suggestion. Let me think about it. The ValueError may appear elsewhere. I will probably define a unique error class so that it won't overlap with other stuffs. Will update here if I make any change.

**Comment by qzhu2017** [comment]
@CompRhys I just made a fix. Now the code should run as following. Please take a look and let me know your opinions.

```python
from pyxtal import pyxtal
from random import choice
from pyxtal.msg import CompatibilityError

for i in range(10):
    try: 
        num = choice([1,2,3,4,5])
        s = pyxtal()
        s.from_random(3, 19, ["C"], [num])
    except CompatibilityError:
        print("bad number", num)

for i in range(10):
    try: 
        num = choice([1,2,3,4,5])
        s = pyxtal(molecular=True)
        s.from_random(3, 19, ["glycine"], [num])
    except CompatibilityError:
        print("bad number", num)
```
