### ISSUE TITLE
RuntimeError: Cannot find the splitter

### ISSUE THREAD

**Issue by cedenoruel** [qzhu2017/PyXtal#156]
Hi everyone!

I wanted to generate possible polymorphic structures of a cocrystal consisting of 2 different molecules. I used the experimental structure as input denoted as 'cocrystal.cif'.

```
from pyxtal import pyxtal
struc = pyxtal(molecular=False)
struc.from_seed('cocrystal.cif') 
struc2 = struc.subgroup_once(H=20) # i tried many groups
```

However, I get **"RuntimeError: Cannot find the splitter"**

Any response would be highly appreciated.

**Comment by qzhu2017** [comment]
Do you want to generate a crystal with subgroup symmetry? If yes, you need to choose the subgroup number that is compatible with the parent structure's symmetry. To reproduce the results, please also upload your cif file.

**Comment by cedenoruel** [comment]
Hi Professor Zhu. Yes, I wanted to generate candidate structures for polymorph screening while maintaining symmetry as much as possible. 

I attached here the cocrystal 
[cocrystal.zip](https://github.com/qzhu2017/PyXtal/files/6911566/cocrystal.zip)

Thank you very much for your time.

**Comment by qzhu2017** [comment]
I am still not clear about your objective. In that cif file, the structure has a space group symmetry of P21 (4). Therefore, its subgroup will be only P1 or P21 (with translation). It doesn't make sense to try any other space group.

If you want to generate candidate structures for polymorph screening, you can use PyXtal to generate random crystals and optimize them with other computational codes. Note that PyXtal only generate trial structures. It does not handle global optimization and energy ranking.
