### ISSUE TITLE
Error: Lattice matrix undefined.

### ISSUE THREAD

**Issue by Reignbeaux** [qzhu2017/PyXtal#173]
I am using PyXtal to generate atomic crystals of various space groups, and for most cases it works perfectly. However, for roughly 1 in 1000 crystals that I generate, I get the warning "Error: Lattice matrix undefined.". I was so far not able to find out why this happens. 

Should I be worried about this? Or is this somehow handled internally? I was thinking about just skipping the structure if this error occurs and retry.

**Comment by qzhu2017** [comment]
Can you show me the exact script and output message?

**Comment by Reignbeaux** [comment]
Here is an example (it doesn't always happen, so I just repeat the random generation 100 times):

```python
from pyxtal import pyxtal

my_crystal = pyxtal()

for i in range(0, 100):
    my_crystal.from_random(
        dim=3, group=14, species=["He"], numIons=[4],
    )
```

This is the warning:
```
UserWarning: Error: Could not generate lattice matrix.

UserWarning: Error: Lattice matrix undefined.
  warn(text)
```

**Comment by qzhu2017** [comment]
@Reignbeaux 
I just made some fix. Can you update the code and run the following with more examples for your application?
```python
from pyxtal import pyxtal

for i in range(0, 100):
    my_crystal = pyxtal()
    my_crystal.from_random(3, 14, ["He"], [4])
    print(i, my_crystal.valid)
```

Ideally, you should use the structure only when `my_crystal.valid=True`

Let me know how it works.

**Comment by Reignbeaux** [comment]
With your code, I now get the exception
```unsupported operand type(s) for *: 'float' and 'NoneType'```
whenever the mentioned warnings occur. `my_crystal.valid` is false. And again, this error only happens sometimes.

**Comment by qzhu2017** [comment]
Great, I am closing this issue now...
