### ISSUE TITLE
pyxtal_test.py fails with missing import of get_layer

### ISSUE THREAD

**Issue by rschireman** [qzhu2017/PyXtal#179]
When installing pyXtal into a conda environment with `pip install --upgrade git+https://github.com/qzhu2017/PyXtal.git@master`, I obtain an ImportError when running the test script:

`ImportError: cannot import name 'get_layer' from 'pyxtal.symmetry'`

It looks like get_layer is not defined in symmetry.py. Perhaps the test script hasn't been updated with the string of recent commits? The line throwing the error in pyxtal_test.py is:

`from pyxtal.symmetry import (
    Group,
    get_wyckoffs,
    get_layer,
    get_rod,
    get_point,
)`

**Comment by qzhu2017** [comment]
This has been fixed in v0.3.9
