### ISSUE TITLE
1d crystal

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal#19]
@scottfredericks 
The implementation should be very straightforward, just need to figure out the relation between rod group and space group.
http://www.cryst.ehu.es/cgi-bin/subperiodic/programs/nph-sub_gen?subtype=rod&from=table

**Comment by qzhu2017** [comment]
@scottfredericks, can you start to work on 1D crystal soon after you are done with the bug fixing of 2D case?

**Comment by scottfredericks** [comment]
@qzhu2017 
I would like to make a Rod group class the same way you have created a layer group class. Do you know of any database which shows the correct permutation information for each group? Or did you calculate the permutations yourself?

In the mean time, I have made a rod.csv file with the Wyckoff positions for each Rod group, and a get_rod function which obtains SymmOps for these positions. I should be able to finish the random_crystal_1D without using the permutation information. But, it might be good to change the code to use the permutation information later, so that it works the same way as the 2D crystal code.

**Comment by qzhu2017** [comment]
Yes, I have done this permutation two years ago. But I couldn't find it. I can retrieve it later.

**Comment by qzhu2017** [comment]
@scottfredericks it is actually good to have a layer.csv as well. Having both permutation and source csv file can allow the cross check on the code.

**Comment by qzhu2017** [comment]
@scottfredericks , please add 1d crystal to the documentation/test scripts when you think this module is ready.

**Comment by scottfredericks** [comment]
@qzhu2017 
I have been struggling figuring out the best way to implement 1D crystals using the existing code, rather than create new functions just for 1D. The functions are very inter-dependent, so I have waited to upload since it would break the existing code.

For 1D crystals, I think we can use the same PBC method you did for obtaining Wyckoff positions and site symmetry, but we'll need to change PBC from a single number to a list of numbers. Also, for this method, we'll need the complete permutation information for the Rod groups. The issue is that the existing code assumes no permutation has been applied, so we still need to transform the crystal after generation.

We could generate the crystal using the standard setting layer and rod groups, but this would require separate functions for 3D, 2D, and 1D, as well as a change to generate_lattice_2D.

I will try to update the functions so they can still work with 3D and 2D first. For 1D, I can create most of the code now, but will need the permutation information before the function can work.

**Comment by qzhu2017** [comment]
@scottfredericks I suggest we do it as what we did on 2D by using the permutation information. I derived the permutation for 2D by myself. We can do the same thing on 1D as well.

**Comment by scottfredericks** [comment]
@qzhu2017 
I have implemented 1D atomic and molecular crystals. I will probably still have to do some more debugging, but all Rod groups generate. Also, I have yet to update the documentation.
Also, it seems the new method for 2D crystals has caused some issues for the resulting symmetry. I will look into it after fixing molecular 3D crystal symmetry.

**Comment by qzhu2017** [comment]
@scottfredericks 
```
qiangzhu@deptanonpool-238:~/Desktop/github/PyXtal$ python pyxtal/test_cases/test_all.py -m 'molecular_1D'
====== Testing functionality for pyXtal version 0.1dev ======
Importing sys...
Success!
Importing numpy...
Success!
Importing pymatgen...
Success!
Importing pandas...
Success!
Importing spglib...
Success!
Importing openbabel...
Success!
Importing pyxtal...
Success!
=== Testing modules ===
pyxtal.database.element
  class Element
pyxtal.database.hall
  hall_from_hm
pyxtal.database.collection
  Collection
pyxtal.database.layergroup
  class Layergroup
pyxtal.operations
  random_vector
  angle
  random_shear_matrix
  is_orthogonal
  aa2matrix
  matrix2aa
  rotate_vector
  are_equal
  class OperationAnalyzer
  class orientation
pyxtal.crystal
  get_wyckoffs (may take a moment)
  get_wyckoff_symmetry (may take a moment)
  get_wyckoffs_generators (may take a moment)
  letter_from_index
  index_from_letter
  jk_from_i
  i_from_jk
  ss_string_from_ops
  random_crystal
  random_crystal_2D
pyxtal.molecule
  ob_mol_from_string
~~~ Error:
Traceback (most recent call last):
  File "pyxtal/test_cases/test_all.py", line 1178, in test_modules
    from pyxtal.molecule import ob_mol_from_string
ImportError: cannot import name 'ob_mol_from_string' from 'pyxtal.molecule' (/Users/qiangzhu/Desktop/github/PyXtal/pyxtal/molecule.py)
~~~ Failed module ~~~
  get_inertia_tensor
~~~ Failed module ~~~
  get_moment_of_inertia
~~~ Failed module ~~~
  reoriented_molecule
~~~ Failed module ~~~
  orientation_in_wyckoff_position
~~~ Failed module ~~~
pyxtal.molecular_crystal
  molecular_crystal
  molecular_crystal_2D
===
One or more modules failed. Try reinstalling the package.
```

**Comment by scottfredericks** [comment]
@qzhu2017 
I forgot to push the change. The testing of openbabel functions should be gone now.

**Comment by qzhu2017** [comment]
@scottfredericks 
Here is another error.
please make sure you also git clone another copy of the code, and run test_all script on that copy.

====== Testing functionality for pyXtal version 0.1dev ======
Importing sys...
Success!
Importing numpy...
Success!
Importing pymatgen...
Success!
Importing pandas...
Success!
Importing spglib...
Success!
Importing openbabel...
Success!
Importing pyxtal...
Success!
=== Testing modules ===
pyxtal.database.element
  class Element
pyxtal.database.hall
  hall_from_hm
pyxtal.database.collection
  Collection
pyxtal.database.layergroup
  class Layergroup
pyxtal.operations
  random_vector
  angle
  random_shear_matrix
  is_orthogonal
  aa2matrix
  matrix2aa
  rotate_vector
  are_equal
  class OperationAnalyzer
  class orientation
pyxtal.crystal
  get_wyckoffs (may take a moment)
  get_wyckoff_symmetry (may take a moment)
  get_wyckoffs_generators (may take a moment)
  letter_from_index
  index_from_letter
  jk_from_i
  i_from_jk
  ss_string_from_ops
  random_crystal
  random_crystal_2D
pyxtal.molecule
  get_inertia_tensor
~~~ Error:
Traceback (most recent call last):
  File "pyxtal/test_cases/test_all.py", line 1186, in test_modules
    get_inertia_tensor(h2o)
NameError: name 'h2o' is not defined
~~~ Failed module ~~~
  get_moment_of_inertia
~~~ Failed module ~~~
  reoriented_molecule
~~~ Failed module ~~~
  orientation_in_wyckoff_position
~~~ Failed module ~~~
pyxtal.molecular_crystal
  molecular_crystal
  molecular_crystal_2D
===
One or more modules failed. Try reinstalling the package.

**Comment by scottfredericks** [comment]
@qzhu2017 
I had forgotten to define the variables h2o and ch4. I have added a function called mol_from_collection to fix this. The module test now works on my system.

However, I have noticed that some structures are still being flagged for incorrect symmetry. So far I've only seen this for 3D molecular and 1D molecular. I will try to diagnose this by this evening.

**Comment by qzhu2017** [comment]
@scottfredericks 
Here is a structure which I noticed by doing molecular_1D. I suspect there is a place which you did not deal with the periodic boundary condition correctly.

<img width="398" alt="image" src="https://user-images.githubusercontent.com/29445366/46120555-159b0880-c1c5-11e8-8496-8adce8f1026e.png">

Please also check how you added the vacuum to the structure. Make sure you add vacuum along a and b axis, not c.
```
1D_Molecular_73.vasp
H48 O24
1.0
10.853217 0.000000 0.000000
-5.426608 9.399161 0.000000
0.000000 0.000000 15.008507
H O
48 24
direct
-0.246796 0.162225 0.449131 H
-0.246796 0.162225 0.550869 H
-0.162225 -0.409021 0.449131 H
-0.162225 -0.409021 0.550869 H
0.409021 0.246796 0.449131 H
0.409021 0.246796 0.550869 H
0.246796 -0.162225 0.449131 H
0.246796 -0.162225 0.550869 H
0.162225 0.409021 0.449131 H
0.162225 0.409021 0.550869 H
-0.409021 -0.246796 0.449131 H
-0.409021 -0.246796 0.550869 H
0.328823 0.081227 0.000000 H
0.247596 -0.081227 0.000000 H
-0.081227 0.247596 0.000000 H
0.081227 0.328823 0.000000 H
-0.247596 -0.328823 0.000000 H
-0.328823 -0.247596 0.000000 H
-0.328823 -0.081227 0.000000 H
-0.247596 0.081227 0.000000 H
0.081227 -0.247596 0.000000 H
-0.081227 -0.328823 0.000000 H
0.247596 0.328823 0.000000 H
0.328823 0.247596 0.000000 H
0.356244 0.000000 0.449131 H
0.356244 -0.000000 0.550869 H
-0.000000 0.356244 0.449131 H
0.000000 0.356244 0.550869 H
-0.356244 -0.356244 0.449131 H
-0.356244 -0.356244 0.550869 H
-0.356244 -0.000000 0.449131 H
-0.356244 0.000000 0.550869 H
0.000000 -0.356244 0.449131 H
-0.000000 -0.356244 0.550869 H
0.356244 0.356244 0.449131 H
0.356244 0.356244 0.550869 H
0.067893 0.276476 0.499980 H
0.208583 0.276476 0.500020 H
-0.276476 -0.208583 0.499980 H
-0.276476 -0.067893 0.500020 H
0.208583 -0.067893 0.499980 H
0.067893 -0.208583 0.500020 H
-0.067893 -0.276476 0.499980 H
-0.208583 -0.276476 0.500020 H
0.276476 0.208583 0.499980 H
0.276476 0.067893 0.500020 H
-0.208583 0.067893 0.499980 H
-0.067893 0.208583 0.500020 H
-0.215054 0.225709 0.500000 O
-0.225709 -0.440763 0.500000 O
0.440763 0.215054 0.500000 O
0.215054 -0.225709 0.500000 O
0.225709 0.440763 0.500000 O
-0.440763 -0.215054 0.500000 O
0.343189 -0.000000 0.000000 O
0.000000 0.343189 0.000000 O
-0.343189 -0.343189 0.000000 O
-0.343189 0.000000 0.000000 O
-0.000000 -0.343189 0.000000 O
0.343189 0.343189 0.000000 O
0.301264 0.000000 0.500000 O
0.000000 0.301264 0.500000 O
-0.301264 -0.301264 0.500000 O
-0.301264 -0.000000 0.500000 O
-0.000000 -0.301264 0.500000 O
0.301264 0.301264 0.500000 O
0.169981 0.339961 0.500000 O
-0.339961 -0.169981 0.500000 O
0.169981 -0.169981 0.500000 O
-0.169981 -0.339961 0.500000 O
0.339961 0.169981 0.500000 O
-0.169981 0.169981 0.500000 O
```

**Comment by scottfredericks** [comment]
@qzhu2017 
With the changes to distance checking, I think these kinds of structures should not generate any more. If we find more structures with short distances, we can open a new issue.
