### ISSUE TITLE
Speedups where possible when specifying lattice.

### ISSUE THREAD

**Issue by InfluenceFunctional** [qzhu2017/PyXtal#193]
Hi there - this isn't a problem with the software (which I quite like) as much as a question about usage.

I'd like to use PyXtal to generate cells / supercells for molecular crystals, providing the molecular geometry **and** lattice information, but not (for now) information on the position / orientation of the molecule. This seems to work on its own, sometimes slower or faster depending on the molecule and lattice settings. I was wondering if there are any tips for running it consistently fast, even if it results in lower fidelity structures. I'm interested specifically in generating very large numbers of proposed cells (within given lattice constraints), very quickly.

**Comment by qzhu2017** [comment]
@InfluenceFunctional  Thanks for your interest in PyXtal. You are right that the speed of structure generation is molecule/lattice-dependent. We created this function and tested the efficiency on several example systems. However, I am not sure how well it is applied to other systems. To answer your question, I suggest you show some of example scripts in the following conversation. This way, I may be able to give you some tips.

**Comment by qzhu2017** [comment]
Hi, @InfluenceFunctional 
It will be great if you can show me two concrete examples that you feel 
(1) the speed is okay
(2) the speed is very slow

This way, I can try and tell you if I can make some improvements.

**Comment by InfluenceFunctional** [comment]
@qzhu2017 ah - makes sense, will-do.

**Comment by InfluenceFunctional** [comment]
@qzhu2017 This is an example I set up with some Z'=1 molecular crystals from the CSD. I'm not concerned with generating the identically matching orientations from the CSD, just generating structures which follow the given cell parameters, which I plan to vary. See attached a minimal script which generates cell geometries and saves the 3x3 supercells, also attached. 

On my machine, the different crystals take widely varying amounts of time, e.g.: 
```
Iter 0 took 1.789 seconds
Iter 1 took 2.553 seconds
Iter 2 took 6.145 seconds
Iter 3 took 0.294 seconds
Iter 4 took 0.386 seconds
Iter 5 took 1.802 seconds
Iter 6 took 0.368 seconds
Iter 7 took 2.531 seconds
Iter 8 took 1.944 seconds
Iter 9 took 0.275 seconds
Iter 10 took 0.626 seconds
Iter 11 took 0.810 seconds
Iter 12 took 0.288 seconds
Iter 13 took 9.578 seconds
Iter 14 took 0.235 seconds
Iter 15 took 15.078 seconds
Iter 16 took 0.849 seconds
Iter 17 took 0.403 seconds
Iter 18 took 12.648 seconds
Iter 19 took 4.102 seconds
```

So in terms of concrete examples, iter 2 at 6 seconds vs. iter 3 at 0.3 seconds is quite a large difference!

It makes sense to me that for some cell types and/or molecular geometries, it will run faster or slower, and looking at some of the structures, just at face-value, the longer-running ones seem to have more involved molecular geometries. Perhaps the application I have in mind is unrealistic / impractical (indeed, I like the software quite a lot- I'm afraid I may be asking too much!), but I don't think it would scale well if there are many samples taking longer than 1 second, unless perhaps I could run many in parallel. 

Could I expect to see speedups from, for example, playing with the tolerances?


[crystal_examples.zip](https://github.com/qzhu2017/PyXtal/files/8577854/crystal_examples.zip)

**Comment by qzhu2017** [comment]
@InfluenceFunctional 
I slightly modified your script to ensure the reproducibility 
```Python
from pyxtal import pyxtal, molecular_crystal, lattice, symmetry
from pymatgen.core import Molecule
from ase.build import make_supercell
import numpy as np
import time
import ase.io as io
from ase.visualize import view
import random

np.random.seed(0)
random.seed(0)

dataset = np.load('crystal_examples.npy',allow_pickle=True).item()

supercells = []
times = []
for i in range(20):
    t0 = time.time()
    crystal = pyxtal(molecular=True)
    mol = Molecule(species=dataset['atom Z'][i], coords=dataset['atom coords'][i])
    sg = symmetry.Group(dataset['crystal spacegroup number and setting'][i][0])
    crystal.from_random(dim=3, 
                        numIons=[dataset['crystal z value'][i]], 
                        species = [mol],
                        group = sg,
                        lattice=lattice.Lattice(ltype=dataset['crystal system'][i],
                                                volume=dataset['molecule volume'][i] * dataset['crystal z value'][i] / 0.65,
                                                matrix=dataset['crystal cell vectors'][i]
                                                )
                        )
    #print(crystal)
    print("Iter {} took {:.3f} seconds".format(i, np.array(time.time() - t0).astype('float16')), len(mol), sg.number, crystal.valid)
    times.append(time.time() - t0)
    supercells.append(make_supercell(crystal.to_ase(), np.eye(3) * 3))
    io.write('crystal_{}.xyz'.format(i),supercells[i])
```
```
Iter 0 took 1.866 seconds 82 2 True
Iter 1 took 6.434 seconds 66 14 True
Iter 2 took 2.324 seconds 50 14 True
Iter 3 took 0.522 seconds 41 2 True
Iter 4 took 0.926 seconds 44 2 True
Iter 5 took 1.478 seconds 93 14 True
Iter 6 took 0.375 seconds 47 14 True
Iter 7 took 1.707 seconds 49 14 True
Iter 8 took 3.561 seconds 111 14 True
Iter 9 took 0.365 seconds 32 14 True
Iter 10 took 0.842 seconds 60 15 True
Iter 11 took 0.801 seconds 68 19 True
Iter 12 took 0.375 seconds 38 19 True
Iter 13 took 13.453 seconds 36 14 True
Iter 14 took 0.187 seconds 42 19 True
Iter 15 took 11.688 seconds 72 14 True
Iter 16 took 0.637 seconds 74 19 True
Iter 17 took 0.379 seconds 49 19 True
Iter 18 took 10.164 seconds 51 14 True
Iter 19 took 2.889 seconds 54 61 True
```
I think you have done everything correctly. Just remember that you always generate something with a random guess. So sometimes it takes many attempts to generate a valid solution. The most expensive part here is the calculation of distance matrix, which was done in Python. Though I have tried very hard to make it faster, the speed won't be too great.

That said, I am not particular worrying about it if it takes less than 1 min to generate a structure. If you run into a system that constantly take more than 1min, please let me know. I am more than happy to take a look. 

If you need to call the generators many times for a given system, I suggest you initialize the molecule, group and lattice objects outside the for loop. This will save you some time.
