### ISSUE TITLE
numpy inconsistence

### ISSUE THREAD

**Issue by zdcao121** [qzhu2017/PyXtal#194]
Hi, it's a great project. 
After installing the pyxtal, I tried to run the simplest example for test  
`from pyxtal import pyxtal`  
But something wrong happened. It seems the version of numpy is not consistent with the pyxtal. Attached is the error info.  

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>  
  File "C:\Users\zdcao\anaconda3\envs\pyxtal\lib\site-packages\pyxtal\__init__.py", line 13, in <module>  
    from pymatgen.core.structure import Structure, Molecule  
  File "C:\Users\zdcao\anaconda3\envs\pyxtal\lib\site-packages\pymatgen\core\__init__.py", line 15, in <module>  
    from .lattice import Lattice  
  File "C:\Users\zdcao\anaconda3\envs\pyxtal\lib\site-packages\pymatgen\core\lattice.py", line 24, in <module>  
    from pymatgen.util.coord import pbc_shortest_vectors  
  File "C:\Users\zdcao\anaconda3\envs\pyxtal\lib\site-packages\pymatgen\util\coord.py", line 16, in <module>  
    from . import coord_cython as cuc  
  File "pymatgen\util\coord_cython.pyx", line 1, in init pymatgen.util.coord_cython  
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

versions info：
`python=3.9.12`
`numpy=1.21.6`
`pyxtal=0.4.5`
`pymatgen=2022.4.26`

Although I tried to install numpy with different versions, it did not  work. Could you tell me how to deal with this problem?

**Comment by qzhu2017** [comment]
I think it is the pymatgen issue. How about you do:
```
pip uninstall pymatgen
```
and then
```
pip install Pymatgen
pip install pyxtal
```

**Comment by zdcao121** [comment]
@qzhu2017 
It still does not work. Even creating a virtual environment and install the Pymatgen before pyxtal, I also meet the same problem.

**Comment by qzhu2017** [comment]
@zdcao121 This is probably due to Python3.9. Can you try to install it in 3.8.x?

**Comment by zdcao121** [comment]
@qzhu2017 I test it in Python 3.8.13 and 3.8.5 on windows, and get the same errors.

**Comment by qzhu2017** [comment]
@zdcao121 
well, I suspect that your `pip uninstall` did not work properly. I suggest the following, 
1, identify the place where you installed pymatgen and numpy. They should be somewhere like 
`C:\Users\zdcao\anaconda3\envs\pyxtal\lib\site-packages`
delete all folders that are related to Pymatgen.
2, type the command like `pip install pymatgen`

**Comment by zdcao121** [comment]
@qzhu2017 I still failed.

**Comment by rpadams** [comment]
Same problem here on Mac.

**Comment by Abhivega** [comment]
Hi, this issue seems to be referenced [here](https://github.com/MaartenGr/BERTopic/issues/392#issue-1092483558). Perhaps creating a new conda env, installing numpy first, and then installing pymatgen could be an option here.

**Comment by qzhu2017** [comment]
@rpadams @zdcao121 
Please take a look at the following link
https://github.com/MaartenGr/BERTopic/issues/392#issue-1092483558

Let me know if it works on your environment.

**Comment by qzhu2017** [comment]
I just tried to install it on my Environment via conda (Linux-ubuntu)

```
conda create --name pyxtal
conda activate pyxtal
conda install --channel conda-forge pymatgen
pip install pyxtal==v0.4.5
```
It works on my environment 
```
Python 3.9.12
numpy 1.21.6
pymatgen 2022.4.26
pyxtal v0.4.5
```

**Comment by zdcao121** [comment]
@qzhu2017 I follow your step in my own computer (Windows 11), and it still failed. But when I test it in the Linux-CentOS, it works  very well. I guess maybe the systemic difference leads to the incompatibility.

**Comment by zdcao121** [comment]
@Youjin1985 It did not work for  Python 3.9.
