### ISSUE TITLE
How to Generate Customed Molecular Crystal Structures.

### ISSUE THREAD

**Issue by songsiwei** [qzhu2017/PyXtal#197]
I am learning to use PyXtal to generate molecular crystal. Online document showed that a random crystal can  be generated using the following code:

my_crystal = pyxtal(molecular=True)
my_crystal.from_random(3, 36, ['H2O'], [4])

However, I want to generate crystal structure according to set of pre-defined parameters, such as molecular positions (the coordiantion of molecular center of mass), cell parameters and even molecular orientations, can PyXtal implement?  Is there any PyXtal tutorials on generating customed molecular crystal.

**Comment by qzhu2017** [comment]
@songsiwei 
yes, you can add most o the pre-defined parameters to constrain the structure generation. I will write a short section to illustrate it later.

**Comment by qzhu2017** [comment]
@songsiwei 
I just updated the document regarding this section
https://pyxtal.readthedocs.io/en/latest/Usage.html#molecular-crystals-with-constraints

I encourage you download the latest version to try it now.
```
 pip install --upgrade git+https://github.com/qzhu2017/PyXtal.git@master
```

You can provide your feedback before we make the next release.

**Comment by songsiwei** [comment]
It works! Thanks you for such a quick response. 
I still have one more puzzle, can the moelcular orientation be controlled when generating crystal structure？

**Comment by qzhu2017** [comment]
@songsiwei This is a bit tricky. Using different reference, you may get different Euler angles. I am gonna hold it for a while.

**Comment by songsiwei** [comment]
Ok. Thank you once again.
