### ISSUE TITLE
Implement the image conversion 

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal#204]
To represent the molecular crystal into an image.

**Comment by qzhu2017** [comment]
Have completed the function. Next is to derive the energy correctly. Now we cannot compute the Hydrogen bonds.

**Comment by qzhu2017** [comment]
Violation occurred on line 60 in file /home/conda/feedstock_root/build_artifacts/rdkit_1635252119815/work/Code/GraphMol/Conformer.cpp
Failed Expression: dp_mol->getNumAtoms() == d_positions.size()

**Comment by sgbaird** [comment]
Could you explain what the image representation is?

**Comment by qzhu2017** [comment]
@sgbaird 
This is different from what you are trying to do. But it may get to merge at some point.

https://nbviewer.org/github/qzhu2017/PyXtal/blob/master/examples/tutorials_notebook/05-crystal-packing.ipynb
