### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Xuruff** [qzhu2017/PyXtal#205]
Hi, 

I only started to delve into python recently and I was curious about PyXtal. I am having some problems installing it and I cant go around them. When I try to install your package through `pip`, the console shows that all requirements are satisfied but it ends by trying to uninstall "llvmlite" and a error pops up, stopping the process. Here is what my console shows:

> Installing collected packages: llvmlite, pooch, numba, ase, pyshtools, pyxtal
>   Attempting uninstall: llvmlite
>     Found existing installation: llvmlite 0.38.0
> Note: you may need to restart the kernel to use updated packages.
> ERROR: Cannot uninstall 'llvmlite'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

Can you help me ? Maybe this is just a rookie mistake :)

**Comment by qzhu2017** [comment]
```
pip install llvmlite --ignore installed
```
and then
```
pip install pyxtal
```

You may interested in the following link:

https://github.com/NVIDIA/NeMo/issues/841
