### ISSUE TITLE
Python v3.10 support

### ISSUE THREAD

**Issue by jacksund** [qzhu2017/PyXtal#206]
Hi all, I was wondering if there are plans to support python 3.10. I would like to use PyXtal in some of my scripts -- but the rest of my setup is dependent on python 3.10 atm. 

Currently, installing with pip on 3.10 fails due to the `llvmlite` package.

**Comment by qzhu2017** [comment]
@jacksund I will check it and let you know by this weekend.

**Comment by jacksund** [comment]
awesome. thank you for taking a look at this

**Comment by qzhu2017** [comment]
@jacksund I just made a new release v0.5.3. It should support python3.10 now.

**Comment by jacksund** [comment]
Thanks for doing this! Helps a bunch :smile:
