### ISSUE TITLE
Spacegroup compatibility not correct

### ISSUE THREAD

**Issue by Youjin1985** [qzhu2017/PyXtal#209]
Hello,
example:  pyxtal_main.py -e Mg,Al,O -n 2,4,8 -s 227
result: pyxtal.msg.Comp_CompatibilityError: Compoisition [2 4 8] not compatible with symmetry 227

But such structure indeed exists (mp-3536):

Mg2 Al4 O8
1.0
-4.085367 -4.085367 0.000000
-4.085367 0.000000 -4.085367
0.000000 -4.085367 -4.085367
Mg Al O
2 4 8
direct
0.750000 0.750000 0.750000 Mg
0.000000 0.000000 0.000000 Mg
0.375000 0.375000 0.875000 Al
0.375000 0.375000 0.375000 Al
0.375000 0.875000 0.375000 Al
0.875000 0.375000 0.375000 Al
0.138629 0.138629 0.138629 O
0.611371 0.611371 0.165887 O
0.165887 0.611371 0.611371 O
0.611371 0.165887 0.611371 O
0.584113 0.138629 0.138629 O
0.138629 0.584113 0.138629 O
0.611371 0.611371 0.611371 O
0.138629 0.138629 0.584113 O

**Comment by Abhivega** [comment]
If you look into the space group [definition](https://www.cryst.ehu.es/cryst/get_wp.html), one can see that the given composition requires a wyckoff position that has a lower multiplicity than the minimum multiplicity offered by the spacegroup 227. You would have to give the composition as [8,16,32]. In fact, if you look at that Materials project [structure](https://materialsproject.org/materials/mp-3536?material_ids=mp-3536), this would be the composition of the conventional filled-cell structure.

**Comment by Youjin1985** [comment]
Yes, I know that [8,16,32] composition is of conventional cell, and [2, 4, 8] if for primitive cell - but for practical applications like fixed composition crystal structure structure prediction it is a real problem.

**Comment by qzhu2017** [comment]
Pyxtal assumes that the crystal structure will take a conventional unit cell representation. 

If you want to use the primitive cell representation, you need to set `conventional=False` as follows

https://github.com/qzhu2017/PyXtal/blob/8facec4c5c7e63f182bf97959e09fc62ef15e808/pyxtal/test_all.py#L680-L681

Btw, I recommend the use of PyXtal as a Python library. 
https://pyxtal.readthedocs.io/en/latest/Usage.html

The `pyxtal_main.py` script is no longer under active maintenance.

**Comment by Youjin1985** [comment]
Thank you so much, I didn't know about that argument.
