### ISSUE TITLE
Error in pyxtal.symmetry module

### ISSUE THREAD

**Issue by ignaspakamore** [qzhu2017/PyXtal#214]
When running the following code for certain space group numbers an error is returned: 
 ```
>>> from pyxtal.symmetry import Group
>>> g = Group(int)
>>> g
-- Spacegroup --# 64 (Cmce)--
16g site symm: 1
8f  site symm: m..
8e  site symm: .2.
8d  site symm: 2..
8c  site symm: -1
4b  site symm: 2/m..
4a  site symm: 2/m..
```

```
Traceback (most recent call last):
  File "/Users/ignaspakamore/miniconda3/lib/python3.9/site-packages/pyxtal-0.5.6-py3.9.egg/pyxtal/symmetry.py", line 297, in __str__
    return self.string
AttributeError: 'Group' object has no attribute 'string'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ignaspakamore/miniconda3/lib/python3.9/site-packages/pyxtal-0.5.6-py3.9.egg/pyxtal/symmetry.py", line 312, in __repr__
    return str(self)
  File "/Users/ignaspakamore/miniconda3/lib/python3.9/site-packages/pyxtal-0.5.6-py3.9.egg/pyxtal/symmetry.py", line 303, in __str__
    ops = ss_string_from_ops(wp.symmetry[0], self.number, dim=self.dim)
  File "/Users/ignaspakamore/miniconda3/lib/python3.9/site-packages/pyxtal-0.5.6-py3.9.egg/pyxtal/symmetry.py", line 2691, in ss_string_from_ops
    if np.isclose(abs(np.dot(opa.axis, axis)), 1):
  File "<__array_function__ internals>", line 180, in dot
TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
```

It seems that it doesn't run for a certain set of space groups: 
143
146
147
148
149
150
152
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194

**Comment by qzhu2017** [comment]
> When running the following code for certain space group numbers an error is returned: 
> 
>  ```
> 
> >>> from pyxtal.symmetry import Group
> 
> >>> g = Group(int)
> 
> >>> g
> 
> -- Spacegroup --# 64 (Cmce)--
> 
> 16g site symm: 1
> 
> 8f  site symm: m..
> 
> 8e  site symm: .2.
> 
> 8d  site symm: 2..
> 
> 8c  site symm: -1
> 
> 4b  site symm: 2/m..
> 
> 4a  site symm: 2/m..
> 
> ```
> 
> 
> 
> ```
> 
> Traceback (most recent call last):
> 
>   File "/Users/ignaspakamore/miniconda3/lib/python3.9/site-packages/pyxtal-0.5.6-py3.9.egg/pyxtal/symmetry.py", line 297, in __str__
> 
>     return self.string
> 
> AttributeError: 'Group' object has no attribute 'string'
> 
> 
> 
> During handling of the above exception, another exception occurred:
> 
> 
> 
> Traceback (most recent call last):
> 
>   File "<stdin>", line 1, in <module>
> 
>   File "/Users/ignaspakamore/miniconda3/lib/python3.9/site-packages/pyxtal-0.5.6-py3.9.egg/pyxtal/symmetry.py", line 312, in __repr__
> 
>     return str(self)
> 
>   File "/Users/ignaspakamore/miniconda3/lib/python3.9/site-packages/pyxtal-0.5.6-py3.9.egg/pyxtal/symmetry.py", line 303, in __str__
> 
>     ops = ss_string_from_ops(wp.symmetry[0], self.number, dim=self.dim)
> 
>   File "/Users/ignaspakamore/miniconda3/lib/python3.9/site-packages/pyxtal-0.5.6-py3.9.egg/pyxtal/symmetry.py", line 2691, in ss_string_from_ops
> 
>     if np.isclose(abs(np.dot(opa.axis, axis)), 1):
> 
>   File "<__array_function__ internals>", line 180, in dot
> 
> TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
> 
> ```
> 
> 
> 
> 
> 
> It seems that it doesn't run for a certain set of space groups: 
> 
> 143
> 
> 146
> 
> 147
> 
> 148
> 
> 149
> 
> 150
> 
> 152
> 
> 154
> 
> 155
> 
> 156
> 
> 157
> 
> 158
> 
> 159
> 
> 160
> 
> 161
> 
> 162
> 
> 163
> 
> 164
> 
> 165
> 
> 166
> 
> 167
> 
> 168
> 
> 173
> 
> 174
> 
> 175
> 
> 176
> 
> 177
> 
> 178
> 
> 179
> 
> 180
> 
> 181
> 
> 182
> 
> 183
> 
> 184
> 
> 185
> 
> 186
> 
> 187
> 
> 188
> 
> 189
> 
> 190
> 
> 191
> 
> 192
> 
> 193
> 
> 194

Sorry for the late reply. This error is probably due to recent change. I will resolve it and get back to you asap.
