### ISSUE TITLE
Does pyxtal work with pyshtools==4.10.3 ? 

### ISSUE THREAD

**Issue by jan-janssen** [qzhu2017/PyXtal#222]
I see that `pyshtools==4.10` is restricted, but I do not really understand why.

**Comment by qzhu2017** [comment]
@jan-janssen  PyXtal used the numba library for XRD calculation. At some point, it created some conflicts with the pyshtools>=v4.10. Hence I intentionally restricted the use of pyxshtools==v4.10. I will lift this restriction if it no longer creates the conflict.

**Comment by qzhu2017** [comment]
I have removed the constraint since pyshtools is now compatible.
