### ISSUE TITLE
Needs to provide our own structure type

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal#23]
@scottfredericks 

Right now, we directly use the structure module from pymatgen, which is good but sometimes not very convenient,
```python
from crystallography.molecular_crystal import molecular_crystal
my_crystal = molecular_crystal(36, ['C60'], [2], 20.0)
my_crystal.struct.to(filename='c60.poscar',fmt='poscar')
my_crystal.struct.to(filename='c60.cif',fmt='cif')
```

the default cif writer does not symmetrize the structure. Pymatgen has a separate cifWriter class to do it. However, it would be better we build our own function inside the crystal class so that the user can directly get the cif file without knowing the functionality in Pymatgen.

I will discuss it with you later in person.

**Comment by qzhu2017** [comment]
@scottfredericks 

An easy way is to write the class to directly inherit from pymatgen structure class. This can be very useful to export files in different ways. 

Plus that, we need to build a molecule class to store the information about:
1, molecular positions/orientation/site symmetry/symmetry operation
2, some lattice transformation from standard space group to nonstandard setting (P21/c -> P21/n)

**Comment by qzhu2017** [comment]
@scottfredericks 
Could you please store the above information for the generated structures? I want to have a test to track the generated Wyckoff positions.

For atomic crystal, we need to know the information regarding the atom in the asymmetric unit: Say,
Na, (x, y, z) positions, mutiplicity+wyckoff letter

For molecular crystal, we need to know each molecule in the asymmetric unit, say,
H2O1, the position for molecular center, multiplicity + wyckoff letter.

**Comment by scottfredericks** [comment]
@qzhu2017 
I have added print_all functions for the random_crystal and molecular_crystal classes. These show the Wyckoff position information.

For atomic crystals, this can be accessed using self.wyckoff_sites. For molecular crystals, this can be accessed using self.mol_sites.

Also, I added a simple euler_from_matrix function to make the molecular orientation information more readable.
