### ISSUE TITLE
Omission of Wyckoff Positions for 2d crystals

### ISSUE THREAD

**Issue by scottfredericks** [qzhu2017/PyXtal#24]
@qzhu2017 
In the function get_wyckoffs, if a Wyckoff position is incompatible with the defined value of PB, it will not include that Wyckoff position into the returned list. As a result, the length of the list can change depending on the value of PB, and thus the indices used for the list might not match up with get_wyckoff_symmetry, get_wyckoff_generators, letter_from_index, index_from_letter, etc.

This has caused various issues for the use of check_wyckoff_position and find_generating_point. I am currently working on syncing up all of these functions so that the correct index will be passed/used. I have made some progress, but it seems there are still a few problems. I will upload the new code once the functions work correctly.

**Comment by scottfredericks** [comment]
@qzhu2017 
Also, I am not sure I understand the criteria for omitting a Wyckoff position based on PBC. I would guess that we should only omit a Wyckoff position if its symmetry includes a translation along the PBC direction. However, it looks like this is not what is coded. Are there other criteria for Layer group Wyckoff positions? And if so, could you explain them?

**Comment by scottfredericks** [comment]
@qzhu2017 
I think the bugs surrounding this issue have been fixed.

There is one other thing to note. Since not all Wyckoff positions are present, the functions letter_from_index and index_from_letter will not generally work when dealing with layer groups, or with 1d groups. Also, care should be taken when comparing Wyckoff position information between 2d and 3d crystals. Other than that, I think everything else works.

I have updated the script 2dmolecular.py, which generates 2d water crystals for every layer group. I am not currently seeing any issues regarding the Wyckoff positions, but I will continue testing.

**Comment by qzhu2017** [comment]
@scottfredericks, a bug in 2d atomic crystal
```
qiangzhu@u-10-240-0-42:~/Desktop/github/crystallography/crystallography/test_cases$ python 2datomic.py 
/Users/qiangzhu/miniconda3/lib/python3.6/site-packages/pymatgen/io/cif.py:44: UserWarning: Please install optional dependency pybtex if youwant to extract references from CIF files.
  warnings.warn("Please install optional dependency pybtex if you"
Testing generation of 2d atomic crystals
Layer group 1...
Traceback (most recent call last):
  File "2datomic.py", line 7, in <module>
    c12 = random_crystal_2D(num, ['C'], [12], 1.0, 1.0)
  File "/Users/qiangzhu/miniconda3/lib/python3.6/site-packages/crystallography/crystal.py", line 1763, in __init__
    self.wyckoffs = deepcopy(get_wyckoffs(self.sg, organized=True, PB=self.PB)) 
TypeError: get_wyckoffs() got an unexpected keyword argument 'PB'
```

**Comment by scottfredericks** [comment]
@qzhu2017 
Seems I missed an instance of get_wyckoffs still using PB instead of PBC. It should be fixed now.

**Comment by qzhu2017** [comment]
@scottfredericks 
It looks like it took a wrong time for some layer groups and end up with a failure. Is there is Wyckoff compatibility check in 2D crystal?
```
qiangzhu@u-10-240-0-42:~/Desktop/github/crystallography/crystallography/test_cases$ python 2datomic.py 
/Users/qiangzhu/miniconda3/lib/python3.6/site-packages/pymatgen/io/cif.py:44: UserWarning: Please install optional dependency pybtex if youwant to extract references from CIF files.
  warnings.warn("Please install optional dependency pybtex if you"
Testing generation of 2d atomic crystals
Layer group 1...
    Success!
Layer group 2...
    Success!
Layer group 3...
    Success!
Layer group 4...
    Success!
Layer group 5...
    Success!
Layer group 6...
    Success!
Layer group 7...
    Success!
Layer group 8...
    Success!
Layer group 9...
    Success!
Layer group 10...
    Success!
Layer group 11...
    Success!
Layer group 12...
    Success!
Layer group 13...
    Success!
Layer group 14...
    Success!
Layer group 15...
    Success!
Layer group 16...
    Success!
Layer group 17...
    Success!
Layer group 18...
    Success!
Layer group 19...
    Success!
Layer group 20...
    Success!
Layer group 21...
    Success!
Layer group 22...
    Success!
Layer group 23...
    Success!
Layer group 24...
    Success!
Layer group 25...
    Success!
Layer group 26...
    Success!
Layer group 27...
    Success!
Layer group 28...
    Success!
Layer group 29...
    Success!
Layer group 30...
    Success!
Layer group 31...
    Success!
Layer group 32...
    Success!
Layer group 33...
    Success!
Layer group 34...
    Success!
Layer group 35...
    Success!
Layer group 36...
    Success!
Layer group 37...
    Success!
Layer group 38...
    Success!
Layer group 39...
    Success!
Layer group 40...
    Success!
Layer group 41...
    Success!
Layer group 42...
    Success!
Layer group 43...
    Failed generation----------------
Layer group 44...
    Success!
Layer group 45...
    Success!
Layer group 46...
    Success!
Layer group 47...
    Failed generation----------------
Layer group 48...
    Success!
Layer group 49...
    Success!
Layer group 50...
    Success!
Layer group 51...
    Failed generation----------------
Layer group 52...
    Success!
Layer group 53...
    Failed generation----------------
Layer group 54...
    Failed generation----------------
Layer group 55...
    Success!
Layer group 56...
    Success!
Layer group 57...
    Success!
Layer group 58...
    Success!
Layer group 59...
    Success!
Layer group 60...
    Success!
Layer group 61...
    Failed generation----------------
Layer group 62...
    Failed generation----------------
Layer group 63...
^[[B^[[B^CTraceback (most recent call last):
  File "2datomic.py", line 7, in <module>
    c12 = random_crystal_2D(num, ['C'], [12], 1.0, 1.0)
  File "/Users/qiangzhu/miniconda3/lib/python3.6/site-packages/crystallography/crystal.py", line 1766, in __init__
    self.generate_crystal()
  File "/Users/qiangzhu/miniconda3/lib/python3.6/site-packages/crystallography/crystal.py", line 1873, in generate_crystal
    coords_toadd, good_merge = merge_coordinate(coords, cell_matrix, self.wyckoffs, self.sg, tol, PBC=self.PBC)
  File "/Users/qiangzhu/miniconda3/lib/python3.6/site-packages/crystallography/crystal.py", line 838, in merge_coordinate
    index = check_wyckoff_position(merged, sg, exact_translation=False, PBC=PBC)
  File "/Users/qiangzhu/miniconda3/lib/python3.6/site-packages/crystallography/crystal.py", line 1445, in check_wyckoff_position
    if are_equal(op_w, op_p, allow_pbc=True):
  File "/Users/qiangzhu/miniconda3/lib/python3.6/site-packages/crystallography/operations.py", line 282, in are_equal
    if not np.allclose(m1, m2, rtol=rtol, atol=atol):
  File "/Users/qiangzhu/miniconda3/lib/python3.6/site-packages/numpy/core/numeric.py", line 2256, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  File "/Users/qiangzhu/miniconda3/lib/python3.6/site-packages/numpy/core/numeric.py", line 2324, in isclose
    y = asanyarray(b)
KeyboardInterrupt

```

**Comment by scottfredericks** [comment]
@qzhu2017 
I think that for these cases a different stoichiometry will have a shorter time to produce a structure. A higher volume should help, but this is related to the issue of refining estimate_volume. Also, I am not sure how to adjust the thickness depending on the layer group, but I imagine it would greatly affect the generation time. Because the estimated volume depends on the stoichiometry, and the ideal thickness depends on the volume, it is difficult to choose a thickness without knowing the volume before hand.

I will adjust the 2datomic script to take these into account.

**Comment by scottfredericks** [comment]
@qzhu2017 
I have updated the script to use a default thickness of 3 angstroms, volume factor of 4, and to use the number of atoms in the general position of each layer group. With these settings, all layer groups generate in a very short time. You can use -t and -f from the command line to adjust the thickness and volume factor. It seems that for most cases, lower values should work just fine, while for others it is still slow.

**Comment by qzhu2017** [comment]
seems have been resolved
