### ISSUE TITLE
Missing `rdkit` package in `requirements.txt`

### ISSUE THREAD

**Issue by samtsevich** [qzhu2017/PyXtal#255]
Hi Qiang,

There is missing `rdkit` library in the `requirements.txt` file – that should be there.

**Comment by qzhu2017** [comment]
@samtsevich 
rdkit is needed only when people want to use smiles string for generating molecular crystals

https://pyxtal.readthedocs.io/en/latest/Usage.html#pyxtal-molecule-pyxtal-molecule
