### ISSUE TITLE
several random 2D structures

### ISSUE THREAD

**Issue by ypanhtu** [qzhu2017/PyXtal#261]
Dear Dr. Zhu

Is it possible to generate several random structures (such as 2D materials with various space group) simultaneously？  

Because the CrySPY code can only do this work for 3D materials rather than 2D materials.  So, it could be nice if the PyXtal can generate the init_POSCARS file which can be used by CrySPY code. 

Thanks so much.

Roc 

HTU

**Comment by qzhu2017** [comment]
https://pyxtal.readthedocs.io/en/latest/Usage.html#random-sub-periodic-crystals

You can checkout this example.

[image: Photograph] <http://www.skarif2.io/>
*Qiang Zhu *Associate Professor
*UNC Charlotte *• Mechanical Engineering
Phone ⋅ +1 702 895 1710
Email ⋅ ***@***.*** ***@***.***>
[image: github]  <https://github.com/qzhu2017>[image: linkedin]
<https://qzhu2017.github.io/>
