### ISSUE TITLE
Corrections on documentations

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal#31]
@scottfredericks 

http://www.physics.unlv.edu/~qzhu/PyXtal/html/#d-molecular-crystals
```python
from pyxtal.crystal import random_crystal
my_crystal = molecular_crystal_2D(20, ['H2O'], [4], 2.0, 2.5)
```
You imported a wrong library here.

**Comment by qzhu2017** [comment]
Here is a more detailed instruction regarding the installation of openbabel in Mac. Somehow, the straight pip install does not work for me. I used a way very similar to the following. 
http://pymatgen.org/installation.html#openbabel-mac-os-x-tested-on-v2-3-2

It would be good to add it in our documentation.

**Comment by scottfredericks** [comment]
@qzhu2017 
I have uploaded updated versions of the documentation. I have addressed these issues, and have rearranged the order of some of the sections. Please let me know if you find any errors.

**Comment by qzhu2017** [comment]
looks good.
