### ISSUE TITLE
An automated script to update the doc file

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal#37]
@scottfredericks 

Just realized that we need to create an automated script to update the sphinx documents. Remember you once showed us that you need to answer some questions when you execute the sphinx commend. So you just need to create a bash script that store all the default answers.  This will make life easier.

**Comment by scottfredericks** [comment]
@qzhu2017 
For future reference:
inside of the doc directory, the following command will update the rst files to include any new python files:
`sphinx-apidoc -o . ../pyxtal -e -M -f`
Once the rst files are satisfactory, or if no new Python files have been added/deleted, you can build the html by running:
`make html`
The html files will be output to /doc/_build/html . Currently, I just copy and paste this folder into the main PyXtal directory for convenience, but this is not necessary.

**Comment by qzhu2017** [comment]
@scottfredericks , in this case, we don't really need two html folders. I suggest we just keep one.

**Comment by scottfredericks** [comment]
@qzhu2017 
I have removed the html folder in the main PyXtal directory. There is still one inside of doc/_build/html. I have also added a README.txt file inside of the doc directory with this information.
