### ISSUE TITLE
Molecular Distance Check

### ISSUE THREAD

**Issue by scottfredericks** [qzhu2017/PyXtal#38]
@qzhu2017 
In order to check the distance between molecules (without checking inter-atomic distances directly), I think minimal ellipsoids would be a good approximate solution. For a given molecule, we can calculate a minimum binding ellipsoid which contains the molecule, with some padding. We can store this ellipsoid as an affine matrix, where the 3x3 rotational/skew part corresponds to the a, b, c vectors of the ellipsoid, and the vector part corresponds to the ellipsoid's center:
```
[a1, a2, a3, v1]
[b1, b2, b3, v2]
[c1, c2, c2, v3]
[0,  0,  0,  1 ]
```
To compare two molecules, we use these two affine 4x4 matrices. We can apply a transformation so that one of the ellipsoids becomes a sphere; the other ellipsoid will be skewed, but will still be an ellipsoid. Then, we can use an approximate method for checking whether or not the sphere and ellipsoid intersect. A more detailed method is described here: https://www.geometrictools.com/Documentation/IntersectionOfEllipsoids.pdf

So, it seems the main challenge is calculating a binding ellipsoid in the first place. I am inexperienced with optimizing functionals computationally. But since we can define the ellipsoid as an affine matrix, I think we can just try to optimize the components of this matrix simultaneously, in such a way that all of our molecular coordinates are contained within the ellipsoid. I will try to look for existing algorithms for this. In the mean time, I will work on a less exact method which uses the binding boxes as a basis for the binding ellipsoid.

Also, there is the issue of doing these checks with periodic boundary conditions. This should be similar to the inter-atomic distance check, but we'll need to apply np.min at a different step in the process.

Because of the complexity of the process compared to direct distance checking, I think the method will likely be slower except for very large molecules. Still, it would be a nice feature to have a binding ellipsoid calculator as part of the package.

**Comment by scottfredericks** [comment]
@qzhu2017 
I have implemented an ellipsoid check for when check_atomic_distances is False. Currently, since I don't have a way to get accurate bounding ellipsoids, the code is significantly slower than the atomic check. But I think this is just because we're overestimating the volume of the molecules; once we have an algorithm for calculating the minimum bounding ellipsoid, it should be faster. Furthermore, I expect the method to be more useful for larger molecules. Once everything is in place, I will try to see how many atoms per molecule are needed before the ellipsoid method becomes faster.

Also, I would like to add a third distance check option which just uses a constant radius (spherical model). In many cases where an ellipsoid could be used, a sphere would work just as well. This should be much faster than either method, regardless of how many atoms there are per molecule. I plan to replace the variable "check_atomic_distances" with a new variable "distance_check". Instead of True or False, the variable can have 3 possible values: "atomic", "ellipsoid", or "sphere".

Like the last update, this only applies to molecular_crystal, and not molecular_crystal_2D or molecular_crystal_1D. I will try to sync up generate_crystal for the 3 classes today.

**Comment by scottfredericks** [comment]
@qzhu2017 
I would also like to note that this is only an approximate ellipsoid checking method. Like the case I showed you at the end of our last meeting, there could be some cases where the ellipsoids may actually overlap, but the algorithm will not detect it, and vice-versa. However, this should only be a small fraction of cases, and a small amount of padding distance should take care of the problem.

I had begun working on an exact analytical method, but it requires calculating the roots of a 6th order polynomial equation, which is obtained via multiplying matrices with polynomial components. It should be possible to implement in theory, but calculating the coefficients of the polynomial would take several pages of calculations. Also, I'm worried that calling np.roots will be significantly slower than the current method.

**Comment by scottfredericks** [comment]
@qzhu2017 
2D and 1D crystals now inherit generate_crystal from the 3D case (for both atomic and molecular). This should make updating the code simpler.

**Comment by qzhu2017** [comment]
@scottfredericks I am not sure I have fully understood the way how you implemented for ellipsoid checking method. I need to spend some time on reading the code. But it would be good to try to play with some large molecule. 
sphere: C60
ellipsoid: ROY
These are available in our molecular library like h2o.
see [our documentation](https://github.com/qzhu2017/PyXtal/blob/master/doc/index.rst)

**Comment by scottfredericks** [comment]
@qzhu2017 
For now, I will work on implementing the Wyckoff class. Once that and the 0d clusters are resolved, I will try to implement an algorithm for finding the minimal enclosing ellipsoid for a given molecule. Here is a reference Matlab algorithm:
https://www.mathworks.com/matlabcentral/fileexchange/9542-minimum-volume-enclosing-ellipsoid
I will also need to work on optimizing the ellipsoid intersection check; it is currently much slower than inter-atomic distance checking, even for C60.

**Comment by qzhu2017** [comment]
@scottfredericks Great. I like this idea of finding the minimal enclosing ellipsoid. But please do it after we are done with the major things.

Please run the script 
```
$ python pyxtal/test_cases/test_3D_molecule.py
```
It will generate a file called out.cif. By looking at these structures, I found many cases where there exist short interatomic distances. Especially for large molecules. For installed I found a couple of cases where C60 has 1.46 Ang C-C distance. You can view them from vesta. If you have problem in visualization, please come to my office tomorrow.

**Comment by scottfredericks** [comment]
@qzhu2017 
I obtained similar results from running the script. I am not sure why this is happening; the minimum distances should be larger than this. It seems the small distances are usually between molecules in the same Wyckoff position, so I think it may be an error in the implementation of check_distance or mol_site.check_distances.

Since I will be re-implementing the tolerance matrices within the next few days, I will double check the code and do some debugging then. Hopefully that will reveal the cause of the issue.

**Comment by qzhu2017** [comment]
@scottfredericks  you are right. You also need to check the distance between the molecule and its periodic images. I think that is how the short distances come.

**Comment by scottfredericks** [comment]
@qzhu2017 
After adding a check between each molecule and its periodic images, it looks like the problem still persists. I will do some more work on the 0D clusters, then take another look at this when I implement the tolerance_matrix class.

**Comment by qzhu2017** [comment]
@scottfredericks 

you are right that extra steps for changing the orientation of the molecule should be allowed (say 30-50 times at most). You can design it either independently or iteratively.
For the independent way, you just generate some random orientations every time.

For the iterative way, you can do something semi-randomly. 
0, generate the random orientation, if there exists small distances. do 2-4 for a maximum cycle of 30-50.
1, You get the distance pair I-j which has smallest distance.
2, rotate the molecule along one of the principle axes (sort by eigenvalues) to force them apart. 
3, randomly rotate the molecules along two other principle axes.

I am not sure if I am clear. You can come to my office tomorrow.

**Comment by qzhu2017** [comment]
@scottfredericks 
to prevent the overlap between the periodic images. A good idea is to make sure that the minimum vector length (a, b, c) is sufficiently long to accommodate the entire molecule.

**Comment by qzhu2017** [comment]
@scottfredericks I just ran the code, and found that the check function takes much longer time for C60 and pentacene.

If you believe the reason is because of the cdist function. I have an easy solution.
When you do the distance check between two molecules, you can choose to not check all atoms. Instead, you can do the followings,
1, choose the direction which these two molecules have the largest separation. 
2, Say, if the direction is x. Remove the atoms which are far from the other molecules. Say, you can choose at most 30 atoms for each cdist calculation.

**Comment by scottfredericks** [comment]
@qzhu2017 
I can try to work on this once the other speedups are implemented; so far I've only added the change to mol_site.check_distances, and am working on check_mol_sites.

I think this may be a feasible solution, it would just take some time to implement, since it couldn't really use much of the existing code. Currently, we don't check the distance between any two molecules directly; instead we create a distance matrix between the atoms of one molecule and the set of atoms for all of the other molecules. To change the atoms used would require a different distance matrix for each molecular pair, including molecules generated by PBC. Because of PBC handling, the existing distance_matrix function could not be used for this method.

It could be done, and would reduce the cumulative matrix size within cdist by a factor of 4. However, we would need to dot every atomic coordinate with the separation vector (which is different for each pair). Also, for certain molecules and orientations, it is possible (but uncommon) for intersections to go undetected with this method.

However, this has made me think that the same idea could be used for PBC checking. Currently, we generate 27 periodic images for one molecule in each molecular pair. Maybe instead, we could only generate the vectors of the PBC translations (not the atomic coordinates), choose the shortest vector, and then check the inter-atomic distances for that one molecular pair. In other words, instead of checking all 27 copies of a molecule, we just check 27 separation vectors, choose the shortest vector for the lattice, and then check one molecule. Though, this carries the same problem - that some molecule shapes may still overlap. So perhaps we could have a cutoff distance based on the molecule's size, and check any pair with a separation less than the cutoff.

Combined, I think these two methods could speed things up by quite a lot, anywhere from 2-100 times, depending on the Wyckoff positions and molecules being checked.

**Comment by scottfredericks** [comment]
@qzhu2017 
I have now added all of the changes which we discussed on Thursday. The script test_3D_molecule.py is still very slow for pentacene and C60. I will now work on your suggestion for checking only some atoms.

I think it will prove to be faster for larger molecules, but slightly slower for others, since we need to do additional calculations. I propose 8 as the number of atoms as the cutoff number for using the new distance checking method. Once the method is implemented, I can do some tests to determine if this is a good cutoff or not.

I think I can implement the new method by Thursday.

**Comment by qzhu2017** [comment]
@scottfredericks I think you can switch to the distance check only when the number of atoms is greater than 30. Please get it done asap. I would like to push you guys to some more important stuffs.

**Comment by qzhu2017** [comment]
@scottfredericks I have updated the test script again. Now the output looks like the following
```
Warning: cannot place chiral molecule in spagegroup
Error: the stoichiometry is incompatible with the wyckoff sites choice
Warning: cannot place chiral molecule in spagegroup
Error: the stoichiometry is incompatible with the wyckoff sites choice
Mol: aspirin     SG:  24 Time: 1.59 seconds, N_attempts:    9 Vol: 4105.34
Warning: cannot place chiral molecule in spagegroup
Error: the stoichiometry is incompatible with the wyckoff sites choice
Mol: aspirin     SG:  80 Time: 0.79 seconds, N_attempts:    4 Vol: 4105.34
Mol: pentacene   SG:  90 Time: 47.79 seconds, N_attempts:  105 Vol: 1653.49
Mol: pentacene   SG:  14 Time: 10.91 seconds, N_attempts:   27 Vol: 1653.49
Mol: pentacene   SG:  48 Time: 5.81 seconds, N_attempts:    1 Vol: 1653.49
Mol: pentacene   SG: 114 Time: 2.38 seconds, N_attempts:   10 Vol: 1653.49
Error: the stoichiometry is incompatible with the wyckoff sites choice
Error: the stoichiometry is incompatible with the wyckoff sites choice
Error: the stoichiometry is incompatible with the wyckoff sites choice
Error: the stoichiometry is incompatible with the wyckoff sites choice
Mol: pentacene   SG: 107 Time: 31.73 seconds, N_attempts:  108 Vol: 3306.98
Mol: pentacene   SG:  86 Time: 4.29 seconds, N_attempts:    3 Vol: 1653.49
Mol: pentacene   SG: 115 Time: 37.36 seconds, N_attempts:  179 Vol: 1653.49
Mol: pentacene   SG: 128 Time: 5.02 seconds, N_attempts:    2 Vol: 1653.49
Mol: pentacene   SG: 118 Time: 5.56 seconds, N_attempts:    3 Vol: 1653.49
Mol: pentacene   SG: 121 Time: 27.54 seconds, N_attempts:   38 Vol: 3306.98
```
I wonder if you can add an option for 
```python
rand_crystal = molecular_crystal(sg, [mol], [4], 1.0)
```
to disable the output of error and warning message. Say, we define a variable called verbosity
verbosity: 0, not output warning/error   
verbosity: 1, not output warning
verbosity: 2, output all

I wonder there should be a convenient mechanism to control the level of output from python.

**Comment by scottfredericks** [comment]
@qzhu2017 
For now I can implement an optional verbosity argument for random_crystal and molecular_crystal (with default 0).

For the future, there is a standard Python module called 'logging' which might be useful. With it, I think it might be possible to use a global verbosity setting, and let us store the things that could be output, but keeping whether to print it optional.

**Comment by qzhu2017** [comment]
@scottfredericks 
After you implementation of fast-checking method, I frequently hit the following message. Please check the structure where the symmetry analyzer returns the error message.
```
qzhu@cms:/scratch/qzhu/github/PyXtal/pyxtal/test_cases$ python test_3D_molecule.py 
Mol:CH4         SG: 39 Time:0.27 seconds, N_attempts:   2 Vol: 433.03
Mol:CH4         SG:119 Time:0.71 seconds, N_attempts:   5 Vol: 433.03
Mol:CH4         SG: 27 Time:0.30 seconds, N_attempts:   1 Vol: 216.51
Mol:CH4         SG: 43 Time:0.18 seconds, N_attempts:   1 Vol: 866.05
Mol:CH4         SG: 88 Time:0.37 seconds, N_attempts:   1 Vol: 433.03
Mol:CH4         SG:  9 Time:0.11 seconds, N_attempts:   2 Vol: 433.03
Mol:CH4         SG: 43 Time:0.18 seconds, N_attempts:   1 Vol: 866.05
Mol:CH4         SG: 44 Time:0.35 seconds, N_attempts:   1 Vol: 433.03
Mol:CH4         SG:166 Time:0.69 seconds, N_attempts:   3 Vol: 649.54
Mol:CH4         SG: 46 Time:0.21 seconds, N_attempts:   1 Vol: 433.03
Mol:H2O         SG: 47 Time:1.00 seconds, N_attempts:   1 Vol: 158.38
Mol:H2O         SG: 80 Time:0.09 seconds, N_attempts:   1 Vol: 316.76
Mol:H2O         SG: 49 Time:0.52 seconds, N_attempts:   1 Vol: 158.38
Mol:H2O         SG: 64 Time:0.26 seconds, N_attempts:   4 Vol: 316.76
Mol:H2O         SG: 90 Time:0.23 seconds, N_attempts:   7 Vol: 158.38
Mol:H2O         SG: 28 Time:0.14 seconds, N_attempts:   3 Vol: 158.38
Mol:H2O         SG: 12 Time:0.30 seconds, N_attempts:   1 Vol: 316.76
Mol:H2O         SG: 44 Time:0.23 seconds, N_attempts:   4 Vol: 316.76
Mol:H2O         SG:  4 Time:0.06 seconds, N_attempts:   2 Vol: 158.38
Mol:H2O         SG:134 Time:0.44 seconds, N_attempts:   1 Vol: 158.38
Mol:NH3         SG: 87 Time:0.36 seconds, N_attempts:   1 Vol: 396.60
Mol:NH3         SG:  9 Time:0.08 seconds, N_attempts:   2 Vol: 396.60
Mol:NH3         SG:191 Time:0.86 seconds, N_attempts:   1 Vol: 198.30
Mol:NH3         SG: 15 Time:0.23 seconds, N_attempts:   1 Vol: 396.60
Mol:NH3         SG: 13 Time:0.26 seconds, N_attempts:   2 Vol: 198.30
Mol:NH3         SG: 55 Time:0.35 seconds, N_attempts:   1 Vol: 198.30
Mol:NH3         SG:101 Time:1.74 seconds, N_attempts: 961 Vol: 198.30
Mol:NH3         SG: 87 Time:0.36 seconds, N_attempts:   1 Vol: 396.60
Mol:NH3         SG:159 Time:0.17 seconds, N_attempts:   2 Vol: 198.30
Mol:NH3         SG: 47 Time:1.00 seconds, N_attempts:   1 Vol: 198.30
Mol:urea        SG: 84 Time:0.41 seconds, N_attempts:   1 Vol: 198.30
Mol:urea        SG: 46 Time:0.15 seconds, N_attempts:   1 Vol: 396.60
Mol:urea        SG: 16 Time:0.70 seconds, N_attempts:   1 Vol: 198.30
Mol:urea        SG: 27 Time:0.20 seconds, N_attempts:   1 Vol: 198.30
Mol:urea        SG:166 Time:0.49 seconds, N_attempts:   4 Vol: 594.90
Mol:urea        SG:155 Time:1.42 seconds, N_attempts: 112 Vol: 594.90
Mol:urea        SG: 17 Time:0.20 seconds, N_attempts:   1 Vol: 198.30
Mol:urea        SG:163 Time:0.39 seconds, N_attempts:   2 Vol: 198.30
Mol:urea        SG:162 Time:0.53 seconds, N_attempts:   2 Vol: 198.30
Mol:urea        SG: 87 Time:0.36 seconds, N_attempts:   1 Vol: 396.60
Mol:benzene     SG: 31 Time:0.31 seconds, N_attempts:   1 Vol: 703.62
Mol:benzene     SG: 29 Time:0.17 seconds, N_attempts:   1 Vol: 703.62
Mol:benzene     SG:112 Time:2.58 seconds, N_attempts:  11 Vol: 703.62
Mol:benzene     SG: 83 Time:1.89 seconds, N_attempts:   9 Vol: 703.62
Mol:benzene     SG: 93 Time:3.00 seconds, N_attempts:  16 Vol: 703.62
Mol:benzene     SG: 28 Time:0.68 seconds, N_attempts:   8 Vol: 703.62
Mol:benzene     SG:  8 Time:0.45 seconds, N_attempts:   4 Vol: 1407.23
Traceback (most recent call last):
  File "test_3D_molecule.py", line 23, in <module>
    content = str(CifWriter(rand_crystal.struct, symprec=0.03))
  File "/scratch/qzhu/anaconda3/lib/python3.7/site-packages/pymatgen/io/cif.py", line 1215, in __init__
    spacegroup = (sf.get_space_group_symbol(),
  File "/scratch/qzhu/anaconda3/lib/python3.7/site-packages/pymatgen/symmetry/analyzer.py", line 136, in get_space_group_symbol
    return self._space_group_data["international"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by qzhu2017** [comment]
<img width="372" alt="image" src="https://user-images.githubusercontent.com/29445366/52895127-c735d880-316a-11e9-9dac-53d4d7f9fadf.png">
This structure is totally wrong. 
Also, please don't allow the fast checking for the small molecules, we should do this only when the number of atoms is greater than 30 or 40.

**Comment by scottfredericks** [comment]
@qzhu2017 
Okay, I will toggle the previous checking method until I can work out these issues.
