### ISSUE TITLE
Primitive cell usage

### ISSUE THREAD

**Issue by scottfredericks** [qzhu2017/PyXtal#41]
@qzhu2017 
Currently, we do not have a way to convert between conventional, primitive, and non-standard settings. I think outputting the conventional standard cell is fine, but working with the primitive cell should speed things up for I, C, and F space groups. For F groups especially, our distance matrices would be reduced in size by a factor of 4**2=16.

I need to research what the primitive cell is for these groups, and how to convert the Wyckoff positions, generators, and symmetry accordingly. Also, we need to convert the final structure to the conventional setting after the primitive structure is generated (with an option whether or not to do so).

For certain classes and functions, we can implement an option like setting='conventional' or setting='primitive'. These include Group, Wyckoff_position, random_crystal, get_wyckoffs, get_wyckoff_generators, get_wyckoff_symmetry, etc.

Further down the line, we could implement more alternative settings, but since we are only outputting structures instead of taking them in, I don't think this will be needed yet. spg and/or pymatgen should have some tools for handling these kinds of problems.

**Comment by qzhu2017** [comment]
@scottfredericks  The conversion between primitive and conventional cells is not unique. There are several ways to do so. I believe pymatgen already has such function. Please check.

It would be good to have an option of `setting`!
