### ISSUE TITLE
Symbol interpretation

### ISSUE THREAD

**Issue by scottfredericks** [qzhu2017/PyXtal#43]
@qzhu2017 
It would be useful to allow the user to input symbols instead of international numbers, since the numbers are not very well known without the use of Bilbao or the International Tables. Also, it would be nice to print the symbol for certain classes.

H-M symbols should be straightforward to implement. Hall symbols may be more complicated. I will worry about those around the time we start incorporating cell transformations.

Symbols will be especially important for 0D clusters, since the non-crystallographic point groups do not have official international numbers. In this case, the Schoenflies notation will probably be the most appropriate.

**Comment by qzhu2017** [comment]
@scottfredericks I suggest we skip the Hall symbols for now. It is really handy to deal with. For cluster, the  the Schönflies symbol is a good option.

**Comment by scottfredericks** [comment]
@qzhu2017 
Okay, for now I will focus on fixing 0D clusters and inter-molecular distance checking.
