### ISSUE TITLE
Repository listed as HTML instead of Python

### ISSUE THREAD

**Issue by scottfredericks** [qzhu2017/PyXtal#44]
@qzhu2017 
I was browsing a few forks of our project, and it seems that the repository is listed as HTML instead of Python. I am not sure if this is automatically detected based on the contents of doc, or if we can change it.

**Comment by qzhu2017** [comment]
@scottfredericks I have added a .gitattribute file to ignore the doc file when GitHub parses the language. However, I don't think this change will apply to those forked repos
