### ISSUE TITLE
Unable to generate ice crystals with molecules on the special positions

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal#47]
@scottfredericks 
I used to be able to generate such crystals without any problem. However, it no longer works now.
```python
from pyxtal.molecular_crystal import molecular_crystal

#para = Lattice.from_para(4.45, 7.70, 7.28, 90, 90, 90)
for i in range(10):
    crystal = molecular_crystal(36, ['H2O'], [2], 2.0)
    crystal.print_all()
```

**Comment by scottfredericks** [comment]
@qzhu2017 
It seems to be an issue with check_images. It is returning False every time. I will try to see why this is.

**Comment by scottfredericks** [comment]
@qzhu2017 
It should be fixed now. There were a couple of issues in the implementation.
