### ISSUE TITLE
cluster distance check

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal#50]
@scottfredericks  
I just quickly ran a test for LJ16, and quickly found a structure with quick high energy (>-9 eV). When I looked at the structure, it clearly show that there exist many rather small distances. 
![image](https://user-images.githubusercontent.com/29445366/53450885-49779580-39d2-11e9-8c48-6e951d64f875.png)

**Comment by scottfredericks** [comment]
@qzhu2017 
I am unable to replicate this issue by generating random clusters. Is that an optimized structure or an unoptimized one?

**Comment by qzhu2017** [comment]
@scottfredericks just committed. You can easily get similar results by running the following command.
```
qzhu@cms:/scratch/qzhu/github/PyXtal/pyxtal/test_cases$ python LJ_bug.py -n 16
```

**Comment by scottfredericks** [comment]
@qzhu2017 
I found and addressed some issues with the handling of lattices for clusters. Also, I have replaced the random_crystal.coordinates attribute with .cart_coords (the absolute coordinates) and .frac_coords (the fractional coordinates), to avoid ambiguity.

Still, I do see the high-energy structures after optimization. However, I cannot tell from the code what the energy is before optimization. I have uploaded a script (pyxtal/test_cases/distance_bug.py), which should detect any inter-atomic distances shorter than 1.07 A. For me, it does not find any.

If the energy is high after optimization, but not before, then I don't see any problem. I have tried calling LJ on the initial positions, but get the following error:

```
Traceback (most recent call last):
  File "LJ_bug.py", line 261, in <module>
    results1 = lj_run.predict(dim=4, maxN=maxN, ncpu=ncpu, pgs=[1])
  File "LJ_bug.py", line 176, in predict
    res.append(self.relaxation(dim, pgs, method, i))
  File "LJ_bug.py", line 189, in relaxation
    eng_before = LJ(pos, dim, method=method)
  File "LJ_bug.py", line 33, in LJ
    pos = np.reshape(pos, (N_atom, dim))
  File "/home/scott/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 279, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/scott/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 48 into shape (4,4)
```

**Comment by qzhu2017** [comment]
@scottfredericks 
I just updated the code. It looks like the high energy is due to the local optimization method failed to find better solution. 
I am closing this issue since the distance is no longer a problem.

**Comment by scottfredericks** [comment]
@qzhu2017 
When running test_all.py, I will occasionally see that the calculated distances are too small. So far, this only seems to happen for clusters; it is possible it has to do with the Wyckoff positions rather than the distance check itself, since it only occurs after re-generating the atomic positions within the Wyckoff position. Instead of calling exit, the program now just exits the structure generation; previously this may have been causing issues with looped structure generation.

**Comment by scottfredericks** [comment]
@qzhu2017 
Updating the point group databases seems to have fixed this issue; I will close it now.
