### ISSUE TITLE
[Typo] Is this a typo?

### ISSUE THREAD

**Issue by yanxon** [qzhu2017/PyXtal#54]
https://github.com/qzhu2017/PyXtal/blob/78c1fe3754c13c801017712b69ae99d927babb64/pyxtal/crystal.py#L2289

**Comment by scottfredericks** [comment]
@yanxon 
Yes, it looks like it is. I am about to do some other commits; I will fix this too.

**Comment by scottfredericks** [comment]
@yanxon 
I have pushed the fix. Let me know if it does not work.
