### ISSUE TITLE
crystal.Lattice.from_para class methos miss 'self' argument

### ISSUE THREAD

**Issue by LuciusV** [qzhu2017/PyXtal#55]
Instead of
def from_para( a, b, c, alpha, beta, gamma, ltype="triclinic", radians=False, PBC=[1,1,1], **kwargs):
should be
def from_para(self, a, b, c, alpha, beta, gamma, ltype="triclinic", radians=False, PBC=[1,1,1], **kwargs):
Only after this fix I get correct lattices.

I think the same is for from_matrix

**Comment by scottfredericks** [comment]
@LuciusV 
I have added the self parameter and classmethod decorators to both of these functions. Hopefully it should work now.

**Comment by LuciusV** [comment]
I have found several similar places in code, could you please check?
line 217, Class Tol_matrix, from_matrix
line 246, Class Tol_matrix, from_radii
line 273, Class Tol_matrix, from_single_value
line 348, Class Tol_matrix, from_file
line 1709, Class Lattice, set_volume

**Comment by qzhu2017** [comment]
@scottfredericks , please correct this change as suggested by Evgeny

**Comment by scottfredericks** [comment]
@qzhu2017 @LuciusV 
Thank you for pointing these issues out; I think all of the class methods are fixed now.
