### ISSUE TITLE
[bug] wyckoff combination 

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal#56]
I was running some test to generate 2D crystal, 
However, the calculation did not progress for a long time, when I tied
5 atoms for layer group 16 (p 2/b11)

Looks like this layer group has only wyckoff positions with 4 and 2 multiplicities. Therefore, odd numbers should be forbidden. But it seems that pyxtal doesn't detect this.

@scottfredericks , could you please check?

**Comment by scottfredericks** [comment]
@qzhu2017 
I uploaded a fix to crystal.py which seems to fix this; I will try and do a more thorough inspection of the code and the issue as soon as I can.

**Comment by scottfredericks** [comment]
@qzhu2017 
I found at least one case for which the code gave the wrong answer (for space group 197, 16 atoms was considered invalid, even though you could use 8c + 8c). I have fixed the algorithm and checked it for all symmetry groups and stoichiometries, up to the multiplicity of the general position. So for example, for space group 225, I checked the output for every number of atoms (for a single atom type, in the conventional cell) up to 192. All combinations now pass.

Also, I noticed that for crystals with multiple atomic or molecular species, it was possible for multiple atom types to try and occupy the same bounded Wyckoff position during check_compatible (bounded meaning the position has no degrees of freedom). This is fixed now, and combinations cannot use the same bounded Wyckoff position more than once. With these changes, check_compatible should work for any stoichiometry now.
