### ISSUE TITLE
Installing pyxtal downgrades pymatgen

### ISSUE THREAD

**Issue by LuciusV** [qzhu2017/PyXtal#64]
Hello,
pyxtal tries to downgrade my pymatgen to <=2019.4.11
Pymatgen is regularly updated, forcing to downgrade it can break things
Please fix the requirements :)

**Comment by qzhu2017** [comment]
I did this intentionally. Somehow, the recent version of pymatgen did not work for some required modules.

**Comment by LuciusV** [comment]
After implicitly preventing it from downgrading pymatgen by installing with
python -m pip install pyxtal pymatgen==2020.1.28
all tests pyxtal_test -m all run fine without any error

**Comment by qzhu2017** [comment]
fix it in f655bb3d956cd4102bd609cd6836ab2a40728377
