### ISSUE TITLE
Suggestion to add a "shake" functionality

### ISSUE THREAD

**Issue by CompRhys** [qzhu2017/PyXtal#71]
Would it be possible to add a "shake" functionality to the code? I.e. given a random crystal with a Wyckoff sequence resample the random offsets. In the event that the current algorithm would combine sites, I would suggest that the offsets be resampled until a suitable structure was found

This would effectively be the same as being able to generate structures given a set of Wyckoff positions

**Comment by qzhu2017** [comment]
@CompRhys Thanks for your suggestion. 

Can you be more specific about the shake functionality?
Say If you want to generate a structure of TiO2, 
http://www.minweb.co.uk/oxides/rutile.html

do you want to ensure that Ti takes 2a and O takes 4f?

**Comment by CompRhys** [comment]
Yes that example is pretty much the use case I have in mind! 

The behaviour I am interested in is that, particularly for larger cells, we might generate random structures with the same set of Wyckoff positions but perhaps the atoms in the structure might have a different Voronoi diagram. I feel that it could be interesting to see how such examples relax to see if anything could be leveraged to make it easier to jump out of local minima

**Comment by qzhu2017** [comment]
Okay, this was actually on my todo list. But never had time to accomplish it. It is good that you asked. I will see if there is a quick resolution based on the existing code.

**Comment by qzhu2017** [comment]
@CompRhys I will add this function some time next week. That said, you are welcome to try to implement this by yourself. 
The places which you need to work on is here


https://github.com/qzhu2017/PyXtal/blob/e89f089d3aec900a5fdf3d543cdf1256054e2811/pyxtal/crystal.py#L573-L580


My student and I wrote this code when we just started to learn Python. I am sure many things can be improved :)

**Comment by CompRhys** [comment]
I will have a look to see if I could implement it, I am still just trying to get a handle on what the code does and where

**Comment by qzhu2017** [comment]
@CompRhys 
I just tried to implement this function in b95e92c810cd3c473499224a7d480384f67a18a8.

Here are some test scripts:
```python
from pyxtal.crystal import random_crystal

my_crystal1 = random_crystal(99, ['Ba','Ti','O'], [1,1,3], 1.0, sites=[["1b"], ["1b"], ["2c", "1b"]])
print(my_crystal1)
my_crystal1.to_file("1.cif")

my_crystal2 = random_crystal(225, ['C'], [3], 1.0, sites=[["4a", "8c"]])
print(my_crystal2)
my_crystal2.to_file("2.cif")

my_crystal3 = random_crystal(225, ['C','Si'], [3, 1], 1.0, sites=[["4a", "8c"], None])
print(my_crystal3)
my_crystal3.to_file("3.cif")
```

In the new version, PyXtal accepts a new optional arg called `sites`, which has to be a list of list. For each specie, one defines a list to tell PyXtal what Wyckoff list will be used. If there is no constraint, simple put `None`.

Can you check if this is what you want? I will also add some checking functions to ensure that the list from the user is valid.

**Comment by CompRhys** [comment]
@qzhu2017 Yes this does exactly what I wanted, thank you!
