### ISSUE TITLE
Inutructuction for pull request

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal#77]
@CompRhys 

Thanks for contributing to PyXtal. I just want to tell you that it would be good to run the test code after you made the changes.

```
qzhu@cms PyXtal (master) $ python scripts/pyxtal_test -m all
```

This will give you some idea if your change is incompatible with the existing code.

**Comment by CompRhys** [comment]
@qzhu2017 Yes sorry! I forgot to make the PR a draft and hadn't gone through and checked whether all the changes were backwards compatible yet

**Comment by qzhu2017** [comment]
@qzhu2017 No problem. Maybe you can send another pull request later. Also, note that I just made some light commits as well.

**Comment by CompRhys** [comment]
shall we close this issue?
