### ISSUE TITLE
issues with the 38 LJ cluster example

### ISSUE THREAD

**Issue by CompRhys** [qzhu2017/PyXtal#79]
After refactoring `crystal.py` I was attempting to replicate the 38 cluster example but in the new code as `wyckoff_attempts` (previously `max3`) is set to 10 by default the code cannot generate structures in C1 with more than 10 atoms without increasing this value. 

Checking back at the code before I made any contributions the example worked previously. I am not sure if I have introduced a bug and there was something previously in place that accounted for this?

**Comment by qzhu2017** [comment]
@CompRhys 
Which script did you run? Is it`LJ_38_Oh.py`?

**Comment by qzhu2017** [comment]
Did you check this commit 197684a5aa300c7d5ad1088b538ea38964a5454f ?
I just ran `LJ_38_Oh.py` and it worked fine.

**Comment by qzhu2017** [comment]
@CompRhys Can you confirm the current status of this issue?

**Comment by CompRhys** [comment]
I am still seeing the issue here my fork is currently level with you but with some cosmetic changes to `LJ_38_Oh.py`. If I try and generate clusters with N larger than `num_wyckoff` attempts is just keeps looping

**Comment by qzhu2017** [comment]
Can you share your modified code here?

**Comment by CompRhys** [comment]
It's available here https://github.com/CompRhys/PyXtal/blob/master/examples/LJ_38_Oh.py but the changes are entirely cosmetic as far as I understand as if I revert to the current script it also doesn't generate in C1 if the cluster is larger than `num_wyckoff`.

**Comment by qzhu2017** [comment]
If you generate 16 atoms with P1 symmetry, it means that you at least need to try 16 Wyckoff positions.

I realize we should have a dynamic assignment of numwyckoffs. This has been fixed in 3b08081

**Comment by CompRhys** [comment]
working!
