### ISSUE TITLE
Getting VXRD Working (Flask app)

### ISSUE THREAD

**Issue by sabaronett** [qzhu2017/PyXtal#85]
@qzhu2017, I'm running into a `FileNotFoundError` when I try to "Visualize" our test NaCl-POSCAR file (see steps and traceback below).

## Steps to (re)produce issue
1. Create and activate new conda virtual environment, installing only Python.
```bash
$ conda create --name pyxtal python
...
$ conda activate pyxtal
(pyxtal) $
```
2. Install PyXtal from its root directory.
```bash
(pyxtal) $ cd PyXtal/
(pyxtal) $ pip install -e .
```
3. Install all Flask requirements per [/flask/README.md](https://github.com/qzhu2017/PyXtal/blob/master/flask/README.md).
```bash
(pyxtal) $ cd flask/
(pyxtal) $ pip install -r requirements.txt
```
4. Launch Flask webserver and visit localhost page in browser.
```bash
(pyxtal) $ flask run
```
5. On "Individual" page (`localhost:5000/individual`), load test file (e.g., `PyXtal/flask/instance/uploads/NaCl-POSCAR`), and click "Visualize" button.

## Flask Error Traceback
![image](https://user-images.githubusercontent.com/51060809/89115585-dd0e8a80-d43e-11ea-9dd0-806c382fe276.png)

## Thoughts
The main exception thrown is essentially,
`FileNotFoundError: [Errno 2] No such file or directory: '/home/stanley/github/qzhu2017/PyXtal/pyxtal/database/atomic_scattering_params.json'`. I remember you mentioning the scattering in the database subdir, which I think is related to this. However, I'm not sure how best to resolve this, e.g., just copying the necessary file(s) from the XRD repo.

Everything else about the Flask app seems to be working by the way, e.g., form field validation checks, website navigation, etc.

Let me know what you think, if you have any questions, or if you'd like me to try something (else). Thanks.

**Comment by qzhu2017** [comment]
I just added the json file to the database. Could you please check?

Today I spent the whole day to implement the visualization stuff. Very glad to have the function!

**Comment by sabaronett** [comment]
@qzhu2017, that did the trick! Everything is working, as far as I can tell! I tested both "individual" and "comparison" with all the different sample upload files. I'll close this issue.

And wow, that's amazing and exciting about all the visualization stuff. Great job!
