### ISSUE TITLE
write setup.py for Automatic installation 

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal#9]
This is not urgent at the moment. But let me put it here for future.
https://docs.python.org/3/distutils/setupscript.html

**Comment by scottfredericks** [comment]
@qzhu2017 
I had some issues managing package subdirectory file paths, but I think it works now. When you get the chance, please see if you are able to build and install the package (via "python setup.py install").

Currently, the package name is "crystallography", and the version is 0.1dev . I am not sure if you want to upload the package to PyPi or not, or if you would like to change the package name.

**Comment by scottfredericks** [comment]
@qzhu2017 
The .py files are now included in manifest.in, and the script uses distutils.core.setup instead of setuptools. Running "python setup.py install" works on my machine.

**Comment by qzhu2017** [comment]
Great. Could you please start to write some guides to illustrate how to use this library after a successful installation? @scottfredericks

**Comment by scottfredericks** [comment]
@qzhu2017 
I will try to upload html files for the existing documentation this evening. For tutorials, I can write about:
*Generating and outputting crystals (3d/2d, atomic/molecular)
*Working with molecules and Wyckoff position/symmetry
*Accessing Wyckoff position and site symmetry information
It seems most of the other functionality is just used within the code for these other functions. Are there any other tutorials you would like me to write for now?

**Comment by qzhu2017** [comment]
@scottfredericks those are more then enough.

**Comment by qzhu2017** [comment]
Crystallography is a long name. Time to think about another name. I have the followings,
PyXtal
Xtallib

Let me know if you have any better proposal.
I am also thinking we can do pip install later after 2d molecular crystal function is ready.

**Comment by qzhu2017** [comment]
@scottfredericks 

There are some confusions in setup.py.
If you use setup from distutils. 
https://docs.python.org/3.6/distutils/setupscript.html

There are no keywords like include_package_data and long_description_content_type.
Moreover, the following line should be rewritten
```python
      package_data={'pyxtal': ['pyxtal.database/*.csv']},
```
to
```python
      package_data={'pyxtal': ['database/*.csv']},
```

In the long run, we should use setuptools, which provides better solution than distutil.
Let's keep the issue open for now.
