### ISSUE TITLE
Improve the orientation_in_wyckoff_position function?

### ISSUE THREAD

**Issue by qzhu2017** [qzhu2017/PyXtal#94]
@scottfredericks 

I know you are probably very busy now. However, it would be nice if you can take a look at the function and try to get rid of some redundant codes there. It works but it is a bit difficult to read.

Let me know if you will have time to do it.

**Comment by scottfredericks** [comment]
I will be busy for a few days, but I might get a chance to work on the
function later in the week. I'll try to let you know if I can by the end of
the weekend, if I haven't already by then.

**Comment by scottfredericks** [comment]
Hi Dr. Zhu,

I will be traveling for work all of next week, and don't expect to have
much time to work on PyXtal. When I find time, I will try let you know.

Best,
Scott

**Comment by qzhu2017** [comment]
No problem. Have a good travel.
